### ISSUE TITLE
Support for defining a custom database file name

### ISSUE THREAD

**Issue by vitusortner** [vitusortner/floor#100]

**Comment by willgsoft** [comment]
Hi, very necessary property.

**Comment by willgsoft** [comment]
When does the update come out?

**Comment by vitusortner** [comment]
Hi @willgsoft, I'm in the process of finalizing my thesis at the moment. Thus I'm very limited in time, which will change in a few days. PRs are welcome!

**Comment by willgsoft** [comment]
Thank you man, I look forward to it.
