### ISSUE TITLE
Add support for DateTime type

### ISSUE THREAD

**Issue by Malrok** [vitusortner/floor#119]
Hi,
I've stumbled upon your library, and being an Android developer I've loved the Room inspiration of it.
I've started introducing it in one of my project, and found out the DateTime type is not supported.
I think it would be great to add this datatype to the ones recognized by the library.
Thanks in advance

**Comment by vitusortner** [comment]
I've thought about introducing type converters similar how [Room](https://developer.android.com/reference/android/arch/persistence/room/TypeConverter.html) handles these conversions. This would open up the possibility of persisting data of custom date implementations, for instance.

**Comment by megasoft78** [comment]
I found a workaround for now using the dart built-in features : 
- var milliseconds = DateTime.now().millisecondsSinceEpoch
- DateTime.fromMillisecondsSinceEpoch(milliseconds)

Not sure why DateTime is not supported. I think SQLite support it as format.
@vitusortner  Do you have some technical limitation here? Why do you need to convert?

**Comment by vitusortner** [comment]
`DateTime` is not supported by sqflite (the database access layer).

Type converters might seem like an overkill for such an easy mapping between milliseconds and Dart's `DateTime`. They surely simplify the interaction with the database. Nevertheless, type converters come in even more handy when thinking about other conversions. For example, whenever an enum value should get stored. It's nicer to just define a type converter in one place and let it do its magic automatically without calling its functions manually.

**Comment by megasoft78** [comment]
Yes, make sense. :)

**Comment by IanDarwin** [comment]
@vitusortner: Further to the above:

> For example, whenever an enum value should get stored.

For the special case of enums, wouldn't it make sense to have floor simply store in an int column, and just convert using myEnum.index and myEnum.values[n]?  

One step up would be to copy the idea from JPA and use an annotation to allow mapping by user's choice of int value or by string name (FWIW, JPA uses @Enumerated(EnumType.STRING) or EnumType.ORDINAL; ORDINAL is the default there). It's well known there that ordinal is more efficient but does mean you can't add new values to the enum except at the end.

This would be simpler than fully implementing type converters and could maybe get in sooner? But meanwhile I've had to convert my entity to use ints for dates (as you suggest) and for enums.

**Comment by vitusortner** [comment]
It's not planned to support `DateTime` out of the box for now. Same for enums. Instead, type converters will be introduced soon which will solve these problems. Follow the progress and discussion in #165.
