### ISSUE TITLE
Ignore specific fields of entities

### ISSUE THREAD

**Issue by vitusortner** [vitusortner/floor#12]
`@Ignore` annotation has to get introduced for this.

**Comment by willgsoft** [comment]
Por favor introducir está etiquetada ya que hay campos que no se requieren en la base de datos.

**Comment by vitusortner** [comment]
I'm on it! Will get released in a few days.

**Comment by willgsoft** [comment]
Muchas gracias es algo importante en mis proyectos, otra cosa que veo que hace falta es el tipo de dato BLOB, revisando la documentación y el código fuente veo que no lo implementa, sería bueno que se agregara.

**Comment by xiprox** [comment]
Hey! Thanks for the great package. Any updates on this?

**Comment by MrMonotone** [comment]
I am interested in this as well. I can use it as a workaround until Converters are implemented.

**Comment by vladchuk** [comment]
Another vote for this. Any timeframe? Thanks!

**Comment by vitusortner** [comment]
Unluckily not at that moment. I'll try to take a look at it as soon as possible.

**Comment by git-xbits** [comment]
Thank you for your package. It's amazing.
Have any idea for a timeframe? Every single model in my project have not mapped attributes aahhaha.
Unfortunately I don't good enough to help you.
