### ISSUE TITLE
[Bug] generate sql with String column bug and suggest using parameter binding

### ISSUE THREAD

**Issue by windrunner414** [vitusortner/floor#120]
Now generated SQL is 'select * from user where id = $id'
It's best to generate like this
```
query('select * from user where id = ?', [id])
```

**Comment by windrunner414** [comment]
It can prevent SQL injection

**Comment by windrunner414** [comment]
It seems have a bug now.
```
@Query('select * from Books where bookName = ":bookName"')
Future<Book> findByName(String bookName);
```
it will throw a error `Parameters of method signature don't match with parameters in the query.`
if write
```
@Query('select * from Books where bookName = :bookName')
```
it can generate successfully but the generated sql is:
```
select * from Books where bookName = $bookName
```
bookName is a String! but this sql does not have quote, it will get a sql compile error

parameter binding is the best solution.Don't need quote and no sql injection

**Comment by vitusortner** [comment]
Thanks for your report! Using sqflite's parameter binding functionality seems to be a better fit, as you already suggested.

**Comment by windrunner414** [comment]
waiting for fix it, now i manually modify generated sql.Thanks for your work

**Comment by vitusortner** [comment]
I've changed the implementation to use the mentioned argument binding functionality of sqflite, which will go into the next release.
