### ISSUE TITLE
(0.4.0) Syntax error in generated code for SQL IN clause

### ISSUE THREAD

**Issue by abhinavc** [vitusortner/floor#126]
Hi Vitus,

The following query
```
@Query("update sports set rated = 1 where id in (:ids)")
  Future<void> setRated(List<int> ids) ;
```

generates the following in the `.part` . Note the missing closing parenthesis in the query - (? instead of (?)

```
 @override
  Future<void> setRated(List<int> ids) async {
    await _queryAdapter
        .queryNoReturn('update sports set rated = 1 where id in (?');
  }
```
This causes the following run-time exception
`DatabaseException(near "?": syntax error (code 1): , while compiling: update sports set rated = 1 where id in (?) sql 'update sports set rated = 1 where id in (?' args []}`

**Comment by abhinavc** [comment]
If this is a valid issue - and easily fixed - then would it be possible to get a hot-fix release?

**Comment by vitusortner** [comment]
Thanks for your report. I'll take a look at it later that day!
