### ISSUE TITLE
Allow query to return objects not entities

### ISSUE THREAD

**Issue by megasoft78** [vitusortner/floor#130]
Hi,
I'm using your amazing package for my first app on Flutter and I'm having an issue.
I want to query the data and return the result of these queries into some objects that are not table.

For instance if I want to have the result of a group by query like this one:

```
Select R.roomName, count(*) as numberOfStudents
from tblRooms R
Inner Join tblStudents S on (S.roomId=R.roomId)
Group By R.roomName
```

I need the possibility to setup a class like this:

```
@View()
class RoomStudentsCountView {
  String roomName;
  int numberOfStudents;

  RoomStudentsCountView (this.roomName, this.numberOfStudents);
}
```

I replaced the @Entity with @View as alternative to describe this type of entity.

I also find sometime that I need the possibility to define field that are not column of the table but just calculated field.
Here's an example:

```
@Entity(tableName: "tblRooms")
class RoomEntity {
  @PrimaryKey(autoGenerate: true)
  int roomId;
  String roomName;

  @CalculatedField()
  int numberOfStudents;

  RoomEntity (this.roomId, this.roomName, this.numberOfStudents);
}
```

I can try to help by looking at the code and try to adapt it but I'm not sure I have enough experience to make it right.

I hope you can help on this. :)

**Comment by vitusortner** [comment]
Hi @megasoft78! I'm happy to see your interest in the package. To your first request: It's planned to support returning objects for queries that are not entities. #33 holds some more information about this feature request. To your second request: This behavior is also planned. #12 describes the feature.

I've seen you forked the repository. Do you plan on implementing the behavior? Would be great to see a PR!

**Comment by megasoft78** [comment]
Hi @vitusortner,
I'm new to Flutter and Dart as I mainly work on C# but I'm looking to implement #12.
My idea is to add a new annotation to ColumnInfo : readonly. I did that but I'm learning where to change the code in order to achieve this feature.
I'm looking for all the CRUD operations and skip the field with readonly annotation for Create, Update and Delete.
Could you give me some info on where to look and how is structured?

**Comment by mqus** [comment]
Hi! the current state of android development pushed me to flutter and yesterday I found your library which seems to perfectly replace room. I would really like to see the `@DatabaseView`s in floor like I had them in room:
```java
@DatabaseView("SELECT collection, artist AS name, group_concat(DISTINCT genre) AS genres, count(*) AS count FROM files GROUP BY artist, collection")
public class Artist {
	String collection;
	String name;
	String genres;
	int count;
}
```
I just got into flutter/dart yesterday, so I can't really help in implementing this but I would really like to see some progress here!

(I know, this is just a wordy +1, but I really want to motivate it!)

**Comment by mqus** [comment]
I think this can be closed now, as 90% of the DatabaseView features are implemented and the remaining 10% (Streams on Views) open a whole new can of worms :)

**Comment by mqus** [comment]
I'm closing this as this seems to be adressed now, with Streams of DatabaseView queries also coming soon.

**Comment by mqus** [comment]
The general issue (parsing the results of arbitrary queries into objects) is tracked in #94

**Comment by moak13** [comment]
Hi, I have a question. Am not totally sound on this but need assistance. I have entities [A, B] created and would like to know how to implement a Join by id from B (child) to A (parent), where both hold a list of items.

**Comment by mqus** [comment]
You could create a database view which has the join as the query and its result columbs as fields. You can then make a query on that view to return the results of that join.

**Comment by ulugbekusmanov** [comment]
> Hi! the current state of android development pushed me to flutter and yesterday I found your library which seems to perfectly replace room. I would really like to see the `@DatabaseView`s in floor like I had them in room:
> 
> ```java
> @DatabaseView("SELECT collection, artist AS name, group_concat(DISTINCT genre) AS genres, count(*) AS count FROM files GROUP BY artist, collection")
> public class Artist {
> 	String collection;
> 	String name;
> 	String genres;
> 	int count;
> }
> ```
> 
> I just got into flutter/dart yesterday, so I can't really help in implementing this but I would really like to see some progress here!
> 
> (I know, this is just a wordy +1, but I really want to motivate it!)

do yo have full example for left join
