### ISSUE TITLE
Support for multilines queries or external resources

### ISSUE THREAD

**Issue by megasoft78** [vitusortner/floor#131]
Hi,
if I need to create a query a bit more complex it's difficult to keep it into a single line. 
Dart support multi line String with """ but it's not working at the moment for the query.
It would be nice to have the possibility to provide the query as an external resource like a text file and use the query name as reference. Not sure is feasible.

Thanks in advance. :)

**Comment by vitusortner** [comment]
I'm investigating the issue right now. The next release will also contain a fix for multiline strings of query annotations.
Could you make the following a bit more precise?
> ... It would be nice to have the possibility to provide the query as an external resource like a text file...

**Comment by megasoft78** [comment]
Hi @vitusortner,
I think when the query became a bit more complex have multiline could be not enough.
The mix between code and sql will make the dao a bit messy.
I was thinking to have a separared text file for each query and in the dao the reference.
Here an example:

File for query : `/queries/students_count_by_room.txt`
```
Select roomId, roomName, count(*) as studentsCount
from tblRooms R
Inner Join tblStudents S on (S.RoomId=R.RoomId)
```

dao : 
@Query(getQuery('/queries/students_count_by_room.txt'))
Future<List<StudentsCountByRoom>> getStudentsCountByRoom();

It's like a fake stored procedure. :)

What do you think?

**Comment by vitusortner** [comment]
Closing issue for now because multiline queries are supported now and it's not planned to implement the functionality for supporting external queries.
