### ISSUE TITLE
(0.5.0) Update with IN not working

### ISSUE THREAD

**Issue by abhinavc** [vitusortner/floor#145]
Hi Vitus, 
Not sure if this is related to #143. But the following query - when called - seems to have no effect

```dart
@Query('update sports set rated = 1 where id in (:ids)')
  Future<void> setRated(List<int> ids);
```
The generated code is 
```dart
@override
  Future<void> setRated(List<int> ids) async {
    await _queryAdapter.queryNoReturn(
        'update sports set rated = 1 where id in (?)',
        arguments: <dynamic>[ids]);
  }
```
In my code, `rated` is a `boolean` column, which I want to set to `true` for rows with given `ids`. And I am doing it as follows 

```dart
// ratedIn is a List<int>, db.sports is the DAO
 await db.sports.setRated(ratedIn); // ratedIn.length = 1 
 List<Sport> rated = await db.sports.rated() ; // @Query("select * from sports where rated = 1")
print(" -- num rated = ${rated.lenth}") ; // prints 0!
```
Am I doing something wrong / missing something? 

Thanks 
Abhinav

**Comment by vitusortner** [comment]
Hi! Sorry for the late reply. Been quite busy over the last weeks. As you have already guessed, this behavior is related to #143. `IN` clauses are currently not supported but I've already started working on it. Thanks for your patience!

**Comment by abhinavc** [comment]
Hi Vitus,
Not to rush you. But by when do you expect to have this feature ready? 

I'm just wondering if I should (a) implement a workaround for now OR (b) write queries as they would be (with IN) and then await the next version in which they'll work as expected

If it's a matter of only a little while, then it'll make sense to do (b). I'll then make allowances during testing accordingly. But if it's a knotty problem that'll take longer to solve, then perhaps (a) would make more sense 

Thanks for your help
Abhinav

**Comment by vitusortner** [comment]
I've just merged this feature into the main branch of the repository and will create a new release tomorrow.
