### ISSUE TITLE
TypeConverters feature

### ISSUE THREAD

**Issue by sanekyy** [vitusortner/floor#155]
Hello. Thanks for great ORM like Room:)
I hope that you already planing to implement TypeConverters support, but just in case I inform you that it will be a very useful feature and I will wait for it very much.

**Comment by vitusortner** [comment]
Hi! Thanks for your interest in the library. Type converters are definitely planned for a future release. Nevertheless, it's tough to say when it will be the case as I'm trying to get the library, as it is, in a stable state to finally release the first production-ready version.
