### ISSUE TITLE
Bug!! inflicting versions of new update

### ISSUE THREAD

**Issue by MahdiPishguy** [vitusortner/floor#157]
Because no versions of floor_generator match >0.5.0 <0.6.0 and floor_generator 0.5.0 depends on floor_annotation ^0.3.1, floor_generator ^0.5.0 requires floor_annotation ^0.3.1.
And because floor >=0.6.0 depends on floor_annotation ^0.4.0, floor_generator ^0.5.0 is incompatible with floor >=0.6.0.
So, because XXXXXXX depends on both floor ^0.6.0 and floor_generator ^0.5.0, version solving failed.

pub get failed (1)

**Comment by vitusortner** [comment]
Thanks for the report! I've missed updating the `floor_generator` version in the README to `^0.6.0`. Please do so in order to get the package up and running.
