### ISSUE TITLE
Query method writer should also handle constructors with named parameters

### ISSUE THREAD

**Issue by vitusortner** [vitusortner/floor#16]

**Comment by windrunner414** [comment]
Is there any plan to achieve it? It's a important feature

**Comment by windrunner414** [comment]
I have to write another facotry constructor to use named parameters now :(

**Comment by vitusortner** [comment]
This feature definitely is planed for a future release of the package. Its implementation could be similar to how the developers of json_serializable realized this behavior ([encode](https://github.com/dart-lang/json_serializable/blob/master/json_serializable/lib/src/encoder_helper.dart), [decode](https://github.com/dart-lang/json_serializable/blob/master/json_serializable/lib/src/decode_helper.dart)).

**Comment by mqus** [comment]
This is solved now, right? I'll close this issue. Pleas reopen if there are some things left to do.
