### ISSUE TITLE
big problem on speed of get query from database

### ISSUE THREAD

**Issue by MahdiPishguy** [vitusortner/floor#162]
after some week as using this library in our application we have a big problem on speed of getting query from database, you suppose we have this part of code:

```dart
child: FutureBuilder(
    future: globals.database.userDao.getUserFuture(),
    builder: (BuildContext context, AsyncSnapshot<User> snapshot) {
      User user = snapshot.data;
      if (snapshot.hasData) {
        if (user == null) {
          /* SECTION 1*/
        } else if (user.userActive == 0) {
          /* SECTION 4*/
        } else {
          /* SECTION 2*/
        }
      } else {
        /* SECTION 3*/
      }
    }),
```

and we suppose we have data in database and `User` table, what happen after run project in `debug` or `release` mode:

after running project we have `SECTION 1` or `SECTION 3` and after that, between 1 or 3 **seconds**!! we have `SECTION 2` or `SECTION 4` ???

why?

```dart

Future<void> main() async {
  globals.database = await $FloorAppDatabase.databaseBuilder('diabetist.db').addMigrations([migration1to2]).build();
...
}





@dao
abstract class UserDao{
  @Query('SELECT * FROM User LIMIT 1')
  Stream<User> getUserStream();

  @Query('SELECT * FROM User LIMIT 1')
  Future<User> getUserFuture();

  ...
}
```

**Comment by vitusortner** [comment]
Hi @MahdiPishguy. I'm unsure where these problems could originate from and will come back to you whenever I found out more.

**Comment by MahdiPishguy** [comment]
@vitusortner this is very big problem and my customers report that for me, i can set simple production for you to test that

**Comment by vitusortner** [comment]
That would be great!

**Comment by mqus** [comment]
I'm currently going through the open issues. What is the state here? can this be closed?

**Comment by mqus** [comment]
As this was open for almost a year now with no further activity I will close this issue. Please reopen if it still persists.
