### ISSUE TITLE
primary key is assumed to be int for update and delete

### ISSUE THREAD

**Issue by North101** [vitusortner/floor#164]
As the title. Everywhere else the primary key is fine but when using commands annotated with @update or @delete they error because it tries to cast the value to int when its not.

**Comment by North101** [comment]
I changed `final int primaryKey` to `final dynamic primaryKey` and `<int>[primaryKey]` to `<dynamic>[primaryKey]` in update_adapter.dart and deletion_adapter.dart and it works fine.

I'm still very new to dart and unfamiliar with the project so I won't open a PR as i'm unsure of any unknown consequences of that change.

**Comment by MahdiPishguy** [comment]
@North101  witch version you are using now?

**Comment by North101** [comment]
I was using `floor: ^0.7.0`. I'm now using my own fork with the following commit: https://github.com/North101/floor/commit/23392ed2f162990cef57d47e0d83388b1ce75d12

**Comment by vitusortner** [comment]
Hi @North101! The changes you've done look fine. Would you mind opening a PR so we could merge these into the library?

**Comment by North101** [comment]
Done. You may also want to restrict PrimaryKey(autoGenerate=true) to ints (if possible)

**Comment by dkaera** [comment]
Hello guys! First I did the same fix, but I found a new one. Update/Delete adapter uses just first item from the primary key list. I have created PR with the fix. Could you review it and leave comments if it's needed. Thanks. 

https://github.com/vitusortner/floor/pull/181
