### ISSUE TITLE
BUG!! order by alwayes is ASC

### ISSUE THREAD

**Issue by MahdiPishguy** [vitusortner/floor#168]
in this query from database i' trying to use order by, but ordering list is `ASC` always 

```dart
  @Query('SELECT * FROM Tickets ORDER BY DESC')
  Stream<List<Tickets>> getTicketsStream();
```

**Comment by vitusortner** [comment]
Hi, I think you also need to define the column whose values should get used for ordering. Like:

`SELECT * FROM Tickets ORDER BY **column** DESC`

**Comment by MahdiPishguy** [comment]
@vitusortner 

yes you have right, this column name as `id` can be default when we use order by?

**Comment by vitusortner** [comment]
This would make things easier. But I don't want to introduce a changed version of SQL for querying Floor databases.

**Comment by MahdiPishguy** [comment]
@vitusortner i'm not sure this problem solved :(

**Comment by vitusortner** [comment]
What kind of problem are you experiencing?
