### ISSUE TITLE
[BUG] Incorrect query compiling

### ISSUE THREAD

**Issue by sanekyy** [vitusortner/floor#171]
Hello.

Bug in query:
@Query('SELECT * FROM Dog WHERE name IN (:names)')
Future<List<Dog>> getAllByNames(List<String> names);

When arguments are substituted in query they are not wrapped in apostrophe ( ' ).

Compiled query for call getAllByNames(["name1", "name2]) will be:

'SELECT * FROM Dog WHERE name IN (name1, name2)'

bur right query is:

'SELECT * FROM Dog WHERE name IN ('name1', 'name2')'

**Comment by vitusortner** [comment]
Thanks for your report! A fix for this will be delivered in the next release.
