### ISSUE TITLE
[BUG] can't generate code

### ISSUE THREAD

**Issue by sanekyy** [vitusortner/floor#172]
Hello.

There is a sample entity:

![image](https://user-images.githubusercontent.com/18647037/61577592-549e9f80-aaf2-11e9-865a-45b065f29717.png)

and there is a sample dao with one query:

![image](https://user-images.githubusercontent.com/18647037/61577597-5e280780-aaf2-11e9-9b56-0c8c8982072b.png)

when I run build_runner build I got an error:

![image](https://user-images.githubusercontent.com/18647037/61577607-739d3180-aaf2-11e9-83d8-6ef48a58e4c5.png)

**Comment by xiprox** [comment]
Hey. Maybe, just maybe, but did you possibly miss the `part ...` line?

**Comment by sanekyy** [comment]
What are you talking about?

**Comment by nafis042** [comment]
@sanekyy  According to the documentation "**These queries have to return either a Future or a Stream of an entity or void**". That means as your entity name is "Dog", so return type of query must be "Future<`Dog`> or something like that.

**Comment by sanekyy** [comment]
Okay, thx.
Will this functionality appear in the future?

**Comment by vitusortner** [comment]
Query methods returning non-entity data types is planned to be in the first stable release of the library. You can follow the current status [here](https://github.com/vitusortner/floor/issues/33).
