### ISSUE TITLE
Support for check conditions

### ISSUE THREAD

**Issue by jmccaull** [vitusortner/floor#177]
I'm fairly new to Dart/Flutter/Sqlite so please bear with me, but I was trying to store some Enums in a side project when I realized that there currently is no support. After some digging, I'm pretty sure the best way to handle this is to set up a check condition on the column? I also figured it would't be much more difficult/different from the nullable property. Would there be any desire for adding this?
Combined with the type converter issue/feature we could probably easily implement default support for enums as well. 
I've worked up a quick pr to add the support and will further implement tests later tonight. Please review the code and let me know what you think. Again, new to dart so pardon any style errors etc, and point them out. Thanks!
https://github.com/vitusortner/floor/pull/176

**Comment by vitusortner** [comment]
Thanks for your contribution to the project!

Some questions that come to my mind:
- As we have a fully-featured programming language in place with Dart, which we could use for these types of checks, why would you still use SQLite checks?
- How do you plan on handling errors that might occur when a check constraint fails? 
- Should check constraints on the table level also be available?

I'll review your PR as soon as possible.

**Comment by jmccaull** [comment]
After some thought, I don't really think this would be useful enums with the type converter - it would be a weird design requirement to need to know to include this property on an enum.
I agree that with good programming practices, the need for something like this is mitigated. I've been trying to find some recommendations toward good practice regarding them and haven't really found much. Putting any logic into the database itself can definitely be a code smell, but I feel like having the option to use the built in functionality is useful. My use case I would probably just set the range constraints for the integer values of the enums, which may end up being redundant when converting back. 
My understanding is the statement is aborted, this should probably be passed on for the user/dev to handle, but I'm not aware if an exception is thrown yet?
I was also considering validation of the check constraint before generating the classes but haven't gotten a chance to see if any is done for the query statements?
I also missed the table level option, again new to sqlite. If you decide this is worth adding it would probably make sense to support both and I'll work on it. In that case would it get added to the entity annotation? Maybe breaking it out from column info into its own annotation that could be placed on fields or classes would make sense? 
Thanks for taking the time to review!
