### ISSUE TITLE
ON DELETE CASCADE

### ISSUE THREAD

**Issue by CiriousJoker** [vitusortner/floor#186]
Is this supported? I didn't find anything in the documentation.

**Comment by vitusortner** [comment]
You can find an example [here](https://github.com/vitusortner/floor/blob/169c5083e5d2e919e287c00ef5d8ea2706a0042d/floor_test/test/model/dog.dart#L12).

https://github.com/vitusortner/floor/blob/169c5083e5d2e919e287c00ef5d8ea2706a0042d/floor_test/test/model/dog.dart#L5-L16
