### ISSUE TITLE
Does this ORM Support syncing Database

### ISSUE THREAD

**Issue by maheshmnj** [vitusortner/floor#198]
It would be really helpful if this ORM supports some kind of way to sync the changes made to offline database ,when the device goes online.Is there any way to efficiently execute the persisting changes that were made to the database while it is offline to an online database

**Comment by vitusortner** [comment]
Such functionality is out of the scope of this library. Nevertheless, you could build the functionality yourself. I would approach the problem by using the [connectivity](https://pub.dev/packages/connectivity) package in order to monitor and react upon network changes.
