### ISSUE TITLE
ForeignKeyAction.SET_NULL invalid create query output

### ISSUE THREAD

**Issue by grinder15** [vitusortner/floor#199]
ItemEntity` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` TEXT, `categoryId` INTEGER, `price` REAL, `servingTypeId` INTEGER, FOREIGN KEY (`categoryId`) REFERENCES `ItemCategoryEntity` (`id`) ON UPDATE NO ACTION ON DELETE SET_NULL, FOREIGN KEY (`servingTypeId`) REFERENCES `ServingTypeEntity` (`id`) ON UPDATE NO ACTION ON DELETE SET_NULL)

It must be "SET NULL" not "SET_NULL"

**Comment by vitusortner** [comment]
Thanks for your report! A fix will be included in the next release.
