### ISSUE TITLE
Incompatibility with inject_generator.

### ISSUE THREAD

**Issue by erluxman** [vitusortner/floor#211]
So the floor_generator does not seem to be compatible with inject_generator. 

Is there any work around ?

**Comment by vitusortner** [comment]
What's the error you're getting?

**Comment by erluxman** [comment]
> Because floor_generator >=0.9.0 depends on analyzer ^0.36.4 and every version of inject_generator from git depends on analyzer ^0.34.0, floor_generator >=0.9.0 is incompatible with inject_generator from git.
> 
> So, because telehealth depends on both inject_generator from git and floor_generator ^0.9.0, version solving failed.
> pub get failed (1)

**Comment by erluxman** [comment]
I fixed it by making a fork from the google repo and updating the analyzer version and then making a release of it. it fixed the issue for me.

You can you this inject git instead 

https://github.com/erluxman/inject.dart
