### ISSUE TITLE
IN in CASE

### ISSUE THREAD

**Issue by abhinavc** [vitusortner/floor#214]
Hi Vitus, 
Am using `0.6.0` (not `0.9.0`) and was trying to implement the following today.

```dart
   @Query("update table set column = case id when in (:ids) then 1 else 0 end")
   Future<void> setColumnTrue(List<int> ids)
```
where `id` is the primary key and `column` is a `boolean` column in `table`.

Also tried 
```dart
   @Query("update table set column = case when id in (:ids) then 1 else 0 end")
   Future<void> setColumnTrue(List<int> ids)
```
Kept getting a SQL compilation error when `ids.isEmpty`.

Hence, was wondering if this is even valid SQL. I couldn't find any documentation that said this wasn't. And if it is indeed valid, then is it / can be supported in `floor`? 

Thanks
Abhinav

**Comment by vitusortner** [comment]
Hi @abhinavc. The second query seems to be the correct one. Are the names you've supplied in the examples above the actual ones? If so, you need to escape them by using backticks. See the SQL query at the bottom.

What is the error message you're getting?

```sql
UPDATE `table` 
SET `column` = CASE 
    WHEN `id` IN (:ids) THEN 1 ELSE 0
    END
```

**Comment by abhinavc** [comment]
Hi Vitus,
The names are representative - not actual. But let me try with back ticks - though that is 
something I haven't had to do till now.

**Comment by abhinavc** [comment]
Hi Vitus,
Sorry, got side-tracked with some other work. But coming back, the update query is doing nothing at all. Using actual names, I have the following defined in my DAO

```dart
 @Query('select * from sports where has_target = 1 order by name asc')
  Future<List<Sport>> targeted() ;

  @Query("update `sports` set `has_target` = case when `id` in (:ids) then 1 else 0 end")
  Future<void> setTargeted(List<int> ids);
```

And to test, I did the following in my code. No change `(after)` providing an `id`

```dart
void func() async {
    List<Sport> targeted = await dao.targeted() ;

    print("--- submit_target: (before)") ;
    targeted.forEach((s) => print(s.name)) ;

    await dao.setTargeted(List<int>(id));
   
    targeted = await dao.targeted() ;
    print("--- submit_target: (after)") ;
    targeted.forEach((s) => print(s.name)) ;
}
```

I can work around this issue by breaking the update query into 2 steps - unsetting all rows and then setting `has_target =  1 where id in (:ids)` (no `case` though). However, if it's valid SQL, then you may want to support it.

Thanks for your help
Abhinav

**Comment by abhinavc** [comment]
Noticed the following run-time error though upon fresh re-build (`flutter clean + run`).
`has_target` is a `boolean` column. Not sure if it has any bearing

```dart
Unhandled Exception: DatabaseException(near "then": syntax error (code 1): , 
while compiling: update sports set has_target = case id in (2) then 1 else 0 end) 
sql 'update sports set has_target = case id in (2) then 1 else 0 end' args []}
```

**Comment by mqus** [comment]
Sorry for keeping quiet so long about this one, do you still have this issue or can this be closed?

**Comment by mqus** [comment]
Closing due to inaction. Please reopen if you disagree :)
