### ISSUE TITLE
Sqlite Encryption

### ISSUE THREAD

**Issue by erluxman** [vitusortner/floor#215]
Is there any way to encrypt the data with floor?

**Comment by vitusortner** [comment]
Hi @erluxman. There currently is no way to do so.

**Comment by zzd258147** [comment]
@erluxman You can use my fork: https://github.com/zzd258147/floor/tree/sqlcipher

Example:
```
  final database = await $FloorFlutterDatabase
      .databaseBuilder('flutter_database.db', 'password')
      .build();
```

**Comment by erluxman** [comment]
@zzd258147  thanks a lot

**Comment by Mohammad-Adam** [comment]
@zzd258147 hi, I'm trying to use your fork, but I get this error when running pub get;
```
Error on line 1, column 7: "name" field doesn't match expected name "sqflite".
  ╷
1 │ name: sqflite_sqlcipher
  │       ^^^^^^^^^^^^^^^^^
  ╵
pub get failed (65;   ╵)
Process finished with exit code 65
```
thanks for your help :)

**Comment by zzd258147** [comment]
@Mohammad-Adam Sorry, my version is out of date.
But you can try this one: https://github.com/kevin-X-lee/floor
Our project is using this one and it works well.

If you have any question, please feel free to contact me.

**Comment by Mohammad-Adam** [comment]
@zzd258147 I'll give it a try, thank you

**Comment by ramsestom** [comment]
@vitusortner 
Would it be possible to have sqlite encryption officialy supported in Floor?
Having to rely on forks that are not maintained up to date with the official version is not really convenient...

**Comment by ramsestom** [comment]
@zzd258147 @Mohammad-Adam 
I looked at the code of https://github.com/kevin-X-lee/floor and I am pretty sure that it actually do not encrypt the sqldatabase with the provided password. 
If you look at the `$FloorDatabase` class generated by the floor_generator, you will see that the `open()` function is not passing the password field to the `DatabaseFactory.openDatabase()` function so you actually endup creating a regular sqlite database with no password encryption at all...

**Comment by omar-adel-7** [comment]
is there any update to support encryption ?

**Comment by Pushplaybang** [comment]
Also looking for official encryption support, is there another open issue for this?

**Comment by deimantasa** [comment]
Curious about encryption as well.

**Comment by RichardRaue** [comment]
Hi. I also would be glad if you could add database encryption to floor. Thanks a lot!

**Comment by vovaklh** [comment]
Also need encryption in floor
