### ISSUE TITLE
Update only one (or selected) columns

### ISSUE THREAD

**Issue by rimidalv** [vitusortner/floor#217]
Hello. Can I update only one or several current fields in a TABLE? 
If NO, could you add this feature?

Thank you.

**Comment by vitusortner** [comment]
Hi @rimidalv. In order to update, for example, the `name` column of a row that is stored in a `person` table (attributes: `id`, `name`), you can use the `@Query` annotation as shown in the following.

```dart
@Query('UPDATE person SET name = :name WHERE id = :id')
Future<void> updateName(String name, int id);
```

**Comment by rimidalv** [comment]
Oo. Great. I'll try. Thank you.
