### ISSUE TITLE
Flutter Column type not supported

### ISSUE THREAD

**Issue by hammad-tariq** [vitusortner/floor#221]
I am using Floor library for persisting dart model classes. and I am facing this problem.

List<String> column type not supported and dynamic column type not supported.

**Comment by alectogeek** [comment]
@hammad-tariq Please provide code, where this problem occurs. Also, provide an output of `flutter doctor -v`

**Comment by mohamedahmedhassan00** [comment]
i have the same issue . and this error refer to Object i used it in the entity

**Comment by vitusortner** [comment]
Floor doesn't support storing lists out of the box. Neither `dynamic` is supported as a column type.

In order to store and retrieve lists, you need to create a one-to-many relationship using [foreign keys](https://github.com/vitusortner/floor#foreign-keys) and retrieve related objects with an additional query.

**Comment by mohamedahmedhassan00** [comment]
Thank you for your response ❤️❤️

**Comment by krabbenprgr** [comment]
Column type is not supported for DateTime.
How to save a date in floor?
 Is there a option to add a typeconverter annotation as in room?

**Comment by vitusortner** [comment]
Type converters are planned to be added (#165, #119), which will also make handling `DateTime` an ease.
In order to save dates as of now, you would need to convert them into integers and the other way round.

```dart
final milliseconds = DateTime.now().millisecondsSinceEpoch
final dateTime = DateTime.fromMillisecondsSinceEpoch(milliseconds)
```

**Comment by Signoutsp26** [comment]
Any option is their to ignore that column which is not supported in floor entity model?

**Comment by alirezat66** [comment]
@hammad-tariq I use a list converter like below and everything works well 
`class ListIntConverter extends TypeConverter<List<int>, String> {
  @override
  List<int> decode(String databaseValue) {
    final jsonFile = json.decode(databaseValue);

    return  List<int>.from(jsonFile['numbers']);
  }

  @override
  String encode(List<int> value) {
     final data = <String, dynamic>{};
    data.addAll({'numbers': value});
    return json.encode(data);
  }
}`
Unfortunately I try to solve it with generic type but it seems the floor don't support it. so you should right single type converter for each type and then add it to database creation class as @typeconvertor
