### ISSUE TITLE
[0.6.0] Incorrect generated query if updating multiple columns

### ISSUE THREAD

**Issue by abhinavc** [vitusortner/floor#223]
Hi Vitus, 
Not sure if this has been fixed in later releases. But I noticed that in `0.6.0` at least, the following
```dart
@Query("update sports set rating = :rating, has_target = :hasTarget, "
      "num_results = :numResults where id = :id")
  Future<void> update(int id, int rating, bool hasTarget, int numResults);
```
results in the following raw query. Note that there should be commas between the 
various arguments 

```dart
@override
  Future<void> update(
      int id, int rating, bool hasTarget, int numResults) async {
    await _queryAdapter.queryNoReturn(
        'update sports set rating = ? has_target = ? num_results = ? where id = ?',
        arguments: <dynamic>[id, rating, hasTarget, numResults]);
  }
```

**Comment by marcjoha** [comment]
Can confirm this is still the case in 0.12.0. Parameters need to be listed in the same order they appear in the SQL string.

**Comment by mqus** [comment]
@marcjoha  the bug here is mainly about the commas, I suppose. Your issue is also valid of course and is mentioned in #224
