### ISSUE TITLE
transaction works incorrectly

### ISSUE THREAD

**Issue by alectogeek** [vitusortner/floor#225]
I have a method marked with @transaction annotation where I fetch some data from the network and do multiple inserts/updates via dao.insert/update (they marked as with @insert and @update methods accordingly). But if one of the operations is aborted, changes are not rolled back. What can cause the problem?

**Comment by mqus** [comment]
Do you still have this problem? If yes, could you please share some code with us to help us reproduce the issue? One idea I have right now: is the method marked with `@transaction` part of a DAO class?

**Comment by mqus** [comment]
Closing due to inaction. Please reopen if you have an update :)
