### ISSUE TITLE
Multiple platform support

### ISSUE THREAD

**Issue by windrunner414** [vitusortner/floor#228]
I know sqflite only support android/ios, so can u consider moor_ffi? it use dart:ffi and support windows/macos/linux/web, or provide a adapter interface not limited to sqflite
I prefer floor's API to moor's

**Comment by luis901101** [comment]
Why is this closed if web is not supported yet?

**Comment by phimath** [comment]
I see this is closed for support for desktop and mobile, but what about web support?  Moor has support for web using IndexedDb under the hood.  Is there any chance of web support in the future?

**Comment by vitusortner** [comment]
Web support would be awesome, I agree! The project is open to contributions.

**Comment by CillianMyles** [comment]
@vitusortner would it be worthwhile to create a "help wanted" type ticket, gather some input on how it could be done, get input & direction from you as maintainer, and then let people read what would be involved and could give it a go if they think they could?

Disclaimer: I am strongly considering using Floor for a project which will most have to support web at some point. If it was something which was fleshed out a bit, and I thought I could do what was needed, I would help out :-)

**Comment by vitusortner** [comment]
Hi @CillianMyles and thanks for bringing this up! Supporting web would be awesome and you offering your help to make this a reality is even better.
I'll take some time in the next few days to write down what seems to be needed. If you have ideas already, feel free to add them to https://github.com/vitusortner/floor/discussions/526. Floor, currently, is pretty tightly coupled with sqflite, which is used as the underlying database access layer. We might consider changing that in the long run.
