### ISSUE TITLE
Static fields should not be included in the mapping

### ISSUE THREAD

**Issue by finger-software** [vitusortner/floor#231]
Currently the static fields are included in
1) Generated CREATE TABLE sql, and
2) Row data mapper.

As example,
```
class Entity {
   static const tableName = 'entity';

   @PrimaryKey(autoGenerate: true)
   final int id;
   final double price;
   Entity(this.id, this.price);
}
```
The generated CREATE TABLE sql for this class looks like
`CREATE TABLE IF NOT EXISTS Entity  (tableName  TEXT, id INTEGER PRIMARY KEY AUTOINCREMENT, price REAL)`

And the row mapper is totally wrong:
```
static final _entityMapper = (Map<String, dynamic> row) => Entity(
      row['tableName'] as int,
      row['id'] as double);
```

**Comment by vitusortner** [comment]
Good catch and thanks for opening a PR to tackle this problem that fast!
