### ISSUE TITLE
Is this project stopped?

### ISSUE THREAD

**Issue by Bwolfs2** [vitusortner/floor#232]
I am trying to run with Mobx but there are errors in dependencies, and I saw that the project is not updated in 4 months.
![image](https://user-images.githubusercontent.com/4654514/72645780-2db31000-3953-11ea-9c80-e0363261405b.png)

**Comment by vitusortner** [comment]
The project is still maintained. I've recently been pretty busy and wasn't able allocate more time for this project.
I've updated all the dependencies, which will resolve the problem you're running into, and I'll release a new version as soon as possible.
