### ISSUE TITLE
missing file database.g.dart in examples folder

### ISSUE THREAD

**Issue by cassioseffrin** [vitusortner/floor#257]
Seems like the database.g.dart is missing 

here is the complete log when I try to run the sample.

Compiler message:
lib/database.dart:9:6: Error: Error when reading 'lib/database.g.dart': No such file or directory
part 'database.g.dart';
     ^
lib/database.dart:9:6: Error: Can't use 'lib/database.g.dart' as a part, because it has no 'part of' declaration.
part 'database.g.dart';
     ^
lib/main.dart:9:26: Error: Getter not found: '$FloorFlutterDatabase'.
  final database = await $FloorFlutterDatabase
                         ^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11.

**Comment by nikpachoo** [comment]
@cassioseffrin, first you need to generate this file. Just run in project folder `flutter packages pub run build_runner build`.

**Comment by cassioseffrin** [comment]
I just realize that I have forget one step: 

flutter packages pub run build_runner build.

This issue can be closed!

**Comment by waleedkalyar** [comment]
hi! I am still facing the issue even after running command of  flutter packages pub run build_runner build in terminal. looks like file is generated in .dart_tool but I can't access it in main file.
getIt.registerSingletonAsync<AppDatabase>(
      () async => FloorAppDatabase.databaseBuilder('notes.db').build());
      Here is the line of code
