### ISSUE TITLE
Bug with nullable bool

### ISSUE THREAD

**Issue by sanekyy** [vitusortner/floor#261]
Hello.

My entity contains nullable bool field.

```dart
@ColumnInfo(nullable: true)
final bool visa;
```

When I call this method with visa == null:

```dart
@Insert(onConflict: OnConflictStrategy.REPLACE)
Future<int> insertOrUpdate(Place place);
```

I got crash:

![image](https://user-images.githubusercontent.com/18647037/74587408-1c692c00-5003-11ea-8e19-a2e0ec099e66.png)

![image](https://user-images.githubusercontent.com/18647037/74587418-2a1eb180-5003-11ea-8bff-0f68e2f16b41.png)

**Comment by mqus** [comment]
I'll fix this asap.
