### ISSUE TITLE
cannot build database on web platform

### ISSUE THREAD

**Issue by mohammadestk** [vitusortner/floor#267]
it seems library does not working on web platform. it's working fine on android and ios.
in below code, app hanging on builder.build.

```
  try {
    final builder = $FloorAppDatabase.databaseBuilder('food.db');
    final database = await builder.build();
  } catch (e) {
    print(e);
  }
```

**Comment by cassioseffrin** [comment]
Although floor sintaxe much better than moor,  I don't see any docs about web support for floor. 

Moor have an experimental web support, take a look: https://moor.simonbinder.eu/web/

I hope the floor project have plans to implement in the future.

**Comment by vitusortner** [comment]
Floor, currently, doesn't support Flutter for web. As of now, it can be used on iOS, Android and macOS.

Closing this in favor of having a single issue for multi-platform support #228
