### ISSUE TITLE
How to run example app

### ISSUE THREAD

**Issue by devpranav2104** [vitusortner/floor#269]
i want to run the example app in my ios simulator. Can you please help me regarding this

**Comment by vitusortner** [comment]
At what step are you stuck? Have you generated the code with `flutter packages pub run build_runner build`?

**Comment by devpranav2104** [comment]
by this command it runs .

**Comment by devpranav2104** [comment]
Thank you it works

**Comment by devpranav2104** [comment]
Thank you it works. Last time i also run this command but it didn't generate code for Dao.This time everything works ok

**Comment by devpranav2104** [comment]
Is it possible to declare private fields in Entity Model?

**Comment by mqus** [comment]
yeah, I'll try to do an example below:

```dart
@entity
class Dog {
  @primaryKey
  final int id;

  final String name;

  @ColumnInfo(name: 'nick_name')
  final String nickName;

  @ColumnInfo(name: 'owner_id')
  final int _ownerId;

  Dog(this.id, this.name, this.nickName, this._ownerId);
}
```
in this case, `_ownerId`would be private and can only be accessed from the same dart file (afaik).

If you have other questions, please open a new issue, I'll be closing this since the original question was solved.
