### ISSUE TITLE
Doesn't work with inheritance

### ISSUE THREAD

**Issue by JCKodel** [vitusortner/floor#270]
All my entities has some common columns:

```dart
abstract class DataEntity {
  DataEntity({@required this.id, this.created, this.updated, this.deleted});

 @PrimaryKey()
  final String id;

  @ColumnInfo(nullable: false)
  final DateTime created;

  @ColumnInfo(nullable: false)
  final DateTime updated;

  @ColumnInfo(nullable: true)
  final DateTime deleted;
}
```

When inheriting from the above class, the code generator fails:

```dart
@Entity(tableName: "Settings", indices: [
  Index(value: ["created"]),
  Index(value: ["updated"]),
  Index(value: ["deleted"]),
])
class Setting extends DataEntity {
  Setting({
    @required String id,
    @required dynamic value,
    DateTime created,
    DateTime updated,
    DateTime deleted,
  })  : this.value = jsonEncode(value),
        super(
          id: id,
          created: created,
          updated: updated,
          deleted: deleted,
        );

  final String value;
}
```

Error:
```
[SEVERE] floor_generator:floor_generator on lib/data/data_context.dart (cached):
Error running FloorGenerator
There is no primary key defined on the entity Setting.
package:meucronogramacapilar/data/setting.dart:21:7
   ╷
21 │ class Setting extends DataEntity {
```

1) Floor should consider inherited classes (specially abstract ones)
2) It would make a lot more sense if there is a Index decorator for columns (so I don't need to declare indices from inherited classes every time)

**Comment by cassioseffrin** [comment]
@vitusortner may you could give us an exemple of how to make proper inherited fields for entities, I cannot found it in docs. I'll appreciate it.

**Comment by mqus** [comment]
DAO inheritance also works already, your `@dao` annotated class just has to extend or implement a class with `@insert` (etc) annotated functions. Please file a new issue if something doesn't work as expected.

**Comment by cassioseffrin** [comment]
That's awesome @mqus. I will appreciate if you could share a simple DAO inheritance sample.

**Comment by mqus** [comment]
I don't have a flutter IDE at hand right now, but here is an example from the tests:

```dart
@dao
abstract class PersonDao extends AbstractDao<Person> {
	@Query('SELECT * FROM person')
	Future<List<Person>> findAllPersons();
}
abstract class AbstractDao<T> extends AnotherAbstractDao<T> {
	@insert
	Future<void> insertItem(T item);
}

abstract class AnotherAbstractDao<T> {
	@update
	Future<void> updateItem(T item);      
}
```

You then have to include `PersonDao` as a getter inside your database class, just as before. 

I don't have an ETA right now but I think this should be included in the README.

**Comment by vitusortner** [comment]
I'll add an example right away 👍

**Comment by sathishmscict** [comment]
> I don't have a flutter IDE at hand right now, but here is an example from the [tests](https://github.com/vitusortner/floor/blob/develop/floor_generator/test/processor/dao_processor_test.dart):
> 
> ```dart
> @dao
> abstract class PersonDao extends AbstractDao<Person> {
> 	@Query('SELECT * FROM person')
> 	Future<List<Person>> findAllPersons();
> }
> abstract class AbstractDao<T> extends AnotherAbstractDao<T> {
> 	@insert
> 	Future<void> insertItem(T item);
> }
> 
> abstract class AnotherAbstractDao<T> {
> 	@update
> 	Future<void> updateItem(T item);      
> }
> ```
> 
> You then have to include `PersonDao` as a getter inside your database class, just as before.
> 
> I don't have an ETA right now but I think this should be included in the README.

While we are using this method.  insertItem  and updateItem methods are not generated in database_file_name.g.dart file.

**Comment by mqus** [comment]
@sathishmscict Can you open a new issue and include at least your DAO code and which version of floor you are using? The example we have in the integration tests at least does not show any issues and the test this exact example is from also does not fail.
