### ISSUE TITLE
How to use ignore annotation?

### ISSUE THREAD

**Issue by sanekyy** [vitusortner/floor#272]

**Comment by mqus** [comment]
Well, you put a `@ignore`(has to be lower case!) before your field(in a class which is marked as an Entity) to make floor ignore it. This means that it will not create a database column for it and your constructor should be able to handle a call without the ignored fields in it. 

But as you didn't specify *what exactly* you don't understand, I can't help you much further.

**Comment by sanekyy** [comment]
Thanks. I can’t find an example with this annotation.

**Comment by sanekyy** [comment]
I can't use this code:(

![image](https://user-images.githubusercontent.com/18647037/75602977-56463200-5adb-11ea-9e6a-af3cd6007001.png)


```
[SEVERE] floor_generator:floor_generator on lib/data/db/app_database.dart:
Error running FloorGenerator
Column type is not supported for BuiltList<Season>.
package:gohere/data/model/db/place.dart:44:25
   ╷
44 │   BuiltList<Season> get seasons {
   │                         ^^^^^^^
   ╵
[INFO] Running build completed, took 15.6s

```

**Comment by vitusortner** [comment]
Thanks for your report! It seems 
Do you see a problem in ignoring **all** getters and setters out of the box? (This will require minor changes.)

**Comment by sanekyy** [comment]
Ignoring all getters and setters may be a good solution.

**Comment by georgefreiri** [comment]
Exemple

 String? nomeDestino;
  @ignore
  EnderecoDestino? enderecoDestino;
  @ignore
  Status? status;
  @ignore
  Servico? servico;
  bool? isColetaComEntrega;
  **@ignore**
  List<Encomenda>? encomendas;
