### ISSUE TITLE
async migration

### ISSUE THREAD

**Issue by sanekyy** [vitusortner/floor#273]
Hello.

Migration is a synchronous function:
![image](https://user-images.githubusercontent.com/18647037/75626620-12862200-5bda-11ea-9b44-36c4fa41abc8.png)

So if we want to execute some operations on database in migrate script with database.execute() we can't await.

But same call in generated code in onCreate calls with await 

![image](https://user-images.githubusercontent.com/18647037/75626659-62fd7f80-5bda-11ea-8888-7424fc852b57.png)

is it normal or bug?

**Comment by vitusortner** [comment]
Good catch! This definitely is unwanted.
