### ISSUE TITLE
[Question] Support data type

### ISSUE THREAD

**Issue by JAICHANGPARK** [vitusortner/floor#274]
Hi now I'm using to floor in my flutter application
What't kind of data type can I use in entity?

1. int -> SQLITE INTEGER?
2. bool -> INTEGER? 
3. string -> TEXT? 
4. datetime -> TEXT?

**Comment by mqus** [comment]
And also Uint8List ->BLOB, if you are using the master branch.

**Comment by vitusortner** [comment]
The project's README has just been updated with a "supported types" section.

**Comment by JAICHANGPARK** [comment]
@vitusortner Thank you
