### ISSUE TITLE
rawQuery must use quote and Dao query don`t effective problems

### ISSUE THREAD

**Issue by brucedong2016** [vitusortner/floor#278]
Hi:
There are two problems when I use this plugin:

1.when I use this rawQuery sql  as bellow: 

> db.database.rawQuery('SELECT * FROM order')

it throw a exception like this: 

> I/flutter (28628): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
> I/flutter (28628): The following SqfliteDatabaseException was thrown:
> I/flutter (28628): DatabaseException(near "order": syntax error (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT
> I/flutter (28628): * FROM order, (OS error - 2:No such file or directory)) sql 'SELECT * FROM order' args []}
> 

it only effective in this patten : 

> db.database.rawQuery('SELECT * FROM \'order\'')

the diference just add the single quote  

2. I defined the Query JPA in Dao class like this:
> @Query('SELECT * FROM order')
> Future<List<Order>> findAllOrders();
when I use the dao query:

> db.orderDao.findAllOrders()

it throw the same exception  ‘near "order": syntax error (Sqlite code 1 SQLITE_ERROR)’

3.the Dao insert methord don`t  appear this error.

I config this floor as the introduction step by step, Should I get some more  informations ? Thank you!

**Comment by IanDarwin** [comment]
"order" is a keyword in all SQL-like languages so it must always be quoted when used as a table or column name.  This is not a Floor-specific query but a general SQL issue applicable to all SQL keywords..

It's generally easier to rename the table to "orders" using the annotation that floor provides.

**Comment by brucedong2016** [comment]
thank you
