### ISSUE TITLE
[Bug] Ignore tag was "ignored" on custom entity getter

### ISSUE THREAD

**Issue by istornz** [vitusortner/floor#282]
Hello,

First thanks for this amazing plugin !

I found a bug related to the @ignore field for a custom getter class.
Infact, the @ignore field seems to be "ignored" (notice the joke 🥇 ) on a custom class getter. 

Here is how to reproduce the bug:

1. Create two entity custom class

```
@entity
class MyMainClass {
  @primaryKey
  final int justAnExample;

  MyMainClass(this.justAnExample);
}
```

```
@entity
class MySecondClass {
  @primaryKey
  final int justAnExample;

  MyMainClass(this.justAnExample);
}
```

2. Create a custom getter & insert the @ignore field inside `MyMainClass`

```

@entity
class MyMainClass {
  @primaryKey
  final int justAnExample;

  MyMainClass(this.justAnExample);
  
  // BEGIN ADDED CODE HERE
  @ignore
  MySecondClass get aParameterToGet {
    MySecondClass aSecondClassFilteredItem;
    // [...] Do stuf here
    return aSecondClassFilteredItem;
  }
  // END ADDED CODE HERE
}
```

3. Run the build command

`flutter packages pub run build_runner build`

You will be noticed by an error like this:

```
[...]
[INFO] 17.4s elapsed, 10/24 actions completed.
[SEVERE] floor_generator:floor_generator on lib/database.dart:
Error running FloorGenerator
Column type is not supported for MySecondClass.
package:myapp/models/aModel.dart:118:15
    ╷
118 │   MySecondClass get aParameterToGet {
    │               ^^^^^^^^^^^^^^
    ╵
[INFO] 19.3s elapsed, 44/60 actions completed.
[INFO] 20.4s elapsed, 115/119 actions completed.
[INFO] Running build completed, took 20.7s
```

So it shouldn't be because the @ignore field was added.

Note: It's working on non custom class getter, so if you create a String getter (normally supported by floor), ignore work well.

Thanks in advance !

**Comment by vitusortner** [comment]
Hi and thanks for your report! This issue will soon be fixed by #279.
