### ISSUE TITLE
Snapshot dependencies don't work

### ISSUE THREAD

**Issue by mqus** [vitusortner/floor#288]
If I try to depend on floor like its written in the Snapshot section in the readme, it will throw the following error:
```
Error on line 21, column 11: Invalid description in the "floor_generator" pubspec on the "floor_annotation" dependency: "../floor_annotation/" is a relative path, but this isn't a local pubspec.
                                                                       
21      path: ../floor_annotation/                                     
              ^^^^^^^^^^^^^^^^^^^^                                     
```                        
Sadly, this does not seem to work, as others have already discovered:
https://stackoverflow.com/questions/54555612/how-to-organise-multi-package-flutter-project-and-use-it-as-dependency

It seems to be covered in this issue: https://github.com/dart-lang/pub/issues/449

Personally, I'll probably work around this by using git submodules in my project.

**Comment by jeanmatthieud** [comment]
I have the same problem.
For development, I cloned the floor repo and created a local dependency.

Even if you cannot fix this bug now, could you create a new release of the library? 
You added a lot of neat features since 0.11.0. A beta release will be enough :)

**Comment by vitusortner** [comment]
I've, for now, removed the snapshot version instructions from the README until we figure something out. #301

**Comment by mqus** [comment]
As talked about in #298 I will be closing this issue since pub simply does not support snapshots as we need them and it doesn't seem to be happening anytime soon:
> I don't think we'll prioritize work on this issue in the short-term future.
> 
> Your best bet might be to make a local check-out and use a path-dependency to that.
(https://github.com/dart-lang/pub/issues/2447#issuecomment-620500711)
