### ISSUE TITLE
DatabaseView generation error with multiline string

### ISSUE THREAD

**Issue by jeanmatthieud** [vitusortner/floor#292]
I'm using the 'develop' branch up to date to use the DatabaseView annotation (thanks by the way !).
It seems that the code generator doesn't work for multiline string requests.
```dart
@DatabaseView("""SELECT X.*
FROM X
GROUP BY X.a""")
```
It's quite surprising as multiline string are working for DAO.

**Comment by mqus** [comment]
Thank you for the report! Could you detail what "Doesn't work"? What exactly happens differently than you expect? Is there an error message?

**Comment by jeanmatthieud** [comment]
```
[SEVERE] floor_generator:floor_generator on lib/db/app_database.dart:
Error formatting generated source code for package:mobile/db/app_database.dart which was output to lib/db/app_database.floor.g.part.
This may indicate an issue in the generated code or in the formatter.
Please check the generated code and file an issue on source_gen if appropriate.
Could not format because the source could not be parsed:

line 67, column 132: Unterminated string literal.
   ╷
67 │               await database.execute('CREATE VIEW IF NOT EXISTS `StopWithRoutes` AS SELECT S.*, group_concat(R._id) as routes_id,
   │                                                                                                                                    ^
   ╵
line 79, column 3: Unterminated string literal.
   ╷
79 │ ');
   │   ^
   ╵
line 83, column 13: Expected to find ')'.
   ╷
83 │             },
   │             ^
   ╵
```

**Comment by jeanmatthieud** [comment]
It works fine if I put the hole string on a single line

**Comment by vitusortner** [comment]
The problem seems to be very similar to what has been described in #131 and got fixed in #133. A fix for multiline view queries is on its way. Thanks for the report!

**Comment by tulioccalazans** [comment]
@jeanmatthieud Hi, How did you configure your pubspec to use "floor" develop branch?

**Comment by jeanmatthieud** [comment]
> @jeanmatthieud Hi, How did you configure your pubspec to use "floor" develop branch?

I wasn't able to do that directly using the GitHub remote repo (one issue is open). I had to clone the repository and edit the pubpec.
I cannot use CI, I'm waiting for the next release of floor...

**Comment by tulioccalazans** [comment]
@jeanmatthieud I forked the project and edited the pubspec myself.
If you want to use it, set it:

```
  floor:
    git:
      url: git://github.com/tulioccalazans/floor.git
      path: floor
      ref: develop
```
