### ISSUE TITLE
Migration does not work on Android.

### ISSUE THREAD

**Issue by Dragonboh** [vitusortner/floor#295]
I have an issue. I have cashed data with pre load views. If login and pass are cashed we don't need to show user all info screens. If i log in on Android device then kill app from app list running and then open app, database return empty data and user need to pass all process again. if i comment Migration it works. On iOS there is not such problem. Does anybody have his?

**Comment by mqus** [comment]
I'm sorry but i'm not sure I understand your problem, let me try to rephrase it:
If you use migrations, then the database will be empty after restarting the app?

Could you share some code, e.g. the migrations you are trying to run and maybe the class with the `@Database` annotation? Without those it will be really hard to try and reproduce your problem, let alone fix it.

**Comment by mqus** [comment]
As there were no answers for two months, I will be closing this issue. If you are still having problems with this, please share some more code with us and reopen the issue!
