### ISSUE TITLE
Can't get @update to work

### ISSUE THREAD

**Issue by marcjoha** [vitusortner/floor#296]
I have a simple entity:

```
@entity
class Website {
  Website(this.url, {this.id});

  @PrimaryKey(autoGenerate: true)
  int id;

  String url;

  int lastChecked;
}
```

Then I do:

```
var website = new Website('http://example.com')
var key = dao.insertWebsite(website);
```

Which works fine, and gives me the generate primary key. But then later I want to update `lastChecked`, so I do:

````
website.lastChecked = getNewTimestamp();
var affectedRows = dao.updateWebsite(website);
````

affectedRows says 1, and my conflict strategy is REPLACE. Still the object doesn't change. I'm guessing this might be related to equality checks but not sure what to do here. Can't find anything in the docs -- can I get a hint here please?

**Comment by mqus** [comment]
With 

> object doesn't change

You mean that the database entry does not change, right? Do you have a minimally reproducable code snippet? 

Anyway, i'll try to reproduce that and get back to you.

**Comment by marcjoha** [comment]
Yes, the database entry is not updated to reflect the change. I'll see if I can share the exact code.

**Comment by marcjoha** [comment]
Experimented a bit more and got it working. My mistake was that I hadn't parameterized all instance variables in my entity. I was using using the constructor `Website(this.url, {this.id})` and had left out `lastChecked`. For posterity and perhaps to others benefit, here's a working code example. 

```
import 'package:floor/floor.dart';
import 'package:floor_update_failure/database.dart';
import 'package:flutter/material.dart';

@entity
class Website {
  Website(this.url, {this.id, this.lastChecked});

  @PrimaryKey(autoGenerate: true)
  int id;

  String url;

  int lastChecked = 0;

  @override
  String toString() {
    return 'Website{id: $id, url: $url, lastChecked: $lastChecked}';
  }
}

@dao
abstract class WebsiteDao {
  @Query('DELETE FROM Website')
  Future<void> deleteAllWebsites();

  @Query('SELECT * FROM Website')
  Future<List<Website>> getWebsites();

  @Query('SELECT * FROM Website WHERE id = :id')
  Future<Website> getWebsite(int id);

  @insert
  Future<int> insertWebsite(Website website);

  @update
  Future<void> updateWebsite(Website website);
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  var db = await $FloorAppDatabase.databaseBuilder('test.db').build();
  await db.websiteDao.deleteAllWebsites();

  var website = Website('http://example.com');
  var key = await db.websiteDao.insertWebsite(website);

  website.id = key;
  website.lastChecked = DateTime.now().millisecondsSinceEpoch;

  await db.websiteDao.updateWebsite(website);

  print(await db.websiteDao.getWebsites());
}
```
Thanks @mqus for offering to help!
