### ISSUE TITLE
Implementing BaseDAO<T>

### ISSUE THREAD

**Issue by SirFilbido** [vitusortner/floor#300]
Hello,

I would like to know if it is possible to implement a DAO in another DAO that has the most common operations to be shared among all DAO.

If so, how do I get my database to generate these extended methods?

Original:
Olá,

Gostaria de saber se é possível implementar um DAO em um outro DAO que possui as operações mais comuns para ser compartilhados entre todos os DAO.

Se sim, como eu faço para que o meu database gere esses métodos que foram estendidos ?

Ex:

```
@dao
abstract class UserDAO extends BaseDAO<User> {
  @Query('SELECT * FROM user WHERE id = :id')
  Future<User> findByIdUser(int id);

  @Query('SELECT * FROM user')
  Future<List<User>> findAllUsers();

  @Query('SELECT * FROM user')
  Stream<List<User>> findAllUsersStream();
}
```

```
@dao
abstract class BaseDAO<T> {
  @insert
  Future<void> create<T>(T object);

  @insert
  Future<void> createList<T>(List<T> object);

  @update
  Future<void> update<T>(T object);

  @update
  Future<void> updateList<T>(List<T> object);

  @delete
  Future<void> delete<T>(T object);

  @delete
  Future<void> deleteList<T>(List<T> object);
}
```

**Comment by mqus** [comment]
This was already adressed in #258 and fixed/implemented in #281.
To use it, just remove the `@dao` from your `BaseDao` and everything should work as expected.
Did you try that already? If yes, what version of floor are you using and what went wrong?

Anyway, we should probably document that feature (and maybe add tests?), So thank you for the report!

**Comment by SirFilbido** [comment]
I made the change you indicated, but the same thing continued, the generated file (app_database.g.dart) still asks for the implementation of the BaseDAO methods.

![image](https://user-images.githubusercontent.com/25982091/77921153-c3351f00-7275-11ea-9b8c-42640074a7a5.png)

The versions are:
floor: ^ 0.11.0
floor_generator: ^ 0.11.0

**Comment by mqus** [comment]
Try to use version 0.12.0, which included that feature and was released 2 days ago ;-) 

> One question, in my User class I use extends or implements ?

Ahh, right, you should use `implements`.

**Comment by SirFilbido** [comment]
Thank you very much @mqus !!!

It worked correctly, the floor is amazing, congratulations !!!

If someone falls into this issue, here's how it went:

```
@dao
abstract class UserDAO extends BaseDAO<User> {
  @Query('SELECT * FROM user WHERE id = :id')
  Future<User> findByIdUser(int id);

  @Query('SELECT * FROM user')
  Future<List<User>> findAllUsers();

  @Query('SELECT * FROM user')
  Stream<List<User>> findAllUsersStream();
}
```

```
abstract class BaseDAO<T> {
  @insert
  Future<void> create(T object);

  @insert
  Future<void> createList(List<T> object);

  @update
  Future<void> update(T object);

  @update
  Future<void> updateList(List<T> object);

  @delete
  Future<void> delete(T object);

  @delete
  Future<void> deleteList(List<T> object);
}
```

The versions:
floor: ^ 0.12.0
floor_generator: ^ 0.12.0
