### ISSUE TITLE
Enable queries that don't return an entity

### ISSUE THREAD

**Issue by vitusortner** [vitusortner/floor#33]
This is required to allow queries like `DELETE FROM Person`.
**It is also required to return objects that are not entities when using `@Query()`.**

**Comment by vitusortner** [comment]
This is party resolved. Methods annotated with `@Query` are now able to be of type `Future<void>`.

**Comment by megasoft78** [comment]
Hi,
I'm trying to run an update using `Future<void>` as return value but I need to pass 2 parameters to the query.
The autogenerated code is using:

`await _queryAdapter.queryNoReturn(`

but it's not passing any parameter. I need to pass 2 parameters that are required by the query.
How can I do it?

Thank you in advance. :)

**Comment by vitusortner** [comment]
Hi @megasoft78! This functionality is currently not supported. I will add it to the next release of the package.

**Comment by megasoft78** [comment]
Thank you. :)

**Comment by vitusortner** [comment]
#132 introduces the new feature into the develop branch.

**Comment by vitusortner** [comment]
Duplicate of #94
