### ISSUE TITLE
Stream did not update after I deleted one row.

### ISSUE THREAD

**Issue by JunCheung** [vitusortner/floor#334]
Stream did not update after I deleted one row.

`@Query('SELECT * FROM House')`
`Stream<List<House>> findAllHousesAsStream();`

version: 0.12.0

**Comment by mqus** [comment]
Thank you for reporting!
Could you please also provide a (minimal) example to reproduce your issue? Do you have multiple DAOs accessing House?, if yes could you show the DAOs (all functions related to House in them)?
I have something in mind but I can't confirm it just from your Stream query function(which looks ok, btw)

**Comment by JunCheung** [comment]
```
@dao
abstract class HouseDao {
  @Query('SELECT * FROM House')
  Future<List<House>> findAllHouses();

  @Query('SELECT * FROM House')
  Stream<List<House>> findAllHousesAsStream();
  
  @Query('SELECT * FROM House where cloudId = :cloudId')
  Future<House> findHouse(int houseId);

  @insert
  Future<void> insertHouse(House house);

  @insert
  Future<void> insertHouses(List<House> houses);

  @update
  Future<void> updateHouse(House house);
    
  @transaction
  Future<void> replaceAllHouses(List<House> houses) async {
    await deleteAllHouses();
    await insertHouses(houses);
  }

  @Query('DELETE FROM House where cloudId = :cloudId')
  Future<void> deleteHouse(int houseId);

  @Query('DELETE FROM House')
  Future<void> deleteAllHouses();
}
```
In widget,
```
@override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: Global.database.houseDao.findAllHousesAsStream(),
      builder: (context, AsyncSnapshot<List<House>> snapshot) {
      }
    );
  }
```
When user click a button, I will call 
```
await Global.database.houseDao.deleteHouse(state.house.cloudId);
``` 
but stream did not update. BTW, Insert is OK.

**Comment by mqus** [comment]
Yeah, I see the issue. 
```dart
@Query('DELETE FROM House where cloudId = :cloudId')
  Future<void> deleteHouse(int houseId);
````

We are currently not analyzing the queries given in `@Query` and expect a `SELECT`- Query there. So if you put a delete-statement in `@Query` then floor thinks that you did something that didn't change the database and won't update the Stream. Is there a reason you didn't use `@delete`? It should do exactly what you want in that case. Only the delete-all-function could be a bit tricky. You could make it accept a List of Houses and get this List through your `findAllHouses` function.

As for analyzing the queries, this is currently planned and slowly worked on.

**Comment by mqus** [comment]
I'm frequently surprised that we mention all of this in the README:wink::
(https://github.com/vitusortner/floor/blob/develop/floor/README.md#limitations-2):
> Only methods annotated with `@insert`, `@update` and `@delete` trigger `Stream` emissions. Inserting data by using the `@Query()` annotation doesn't.

**Comment by JunCheung** [comment]
Got it. I saw deletion in query: https://github.com/vitusortner/floor/blob/develop/floor/README.md#queries, so I use `@Query` for the deletion. I will update my code. 

Thanks.

**Comment by JunCheung** [comment]
Can I use `@delete` with primary key only but not the object?

**Comment by mqus** [comment]
No, that is currently not possible.

**Comment by JunCheung** [comment]
Ok, Thanks.

**Comment by dmba** [comment]
Here is a workaround, based on discussion above. Hope it will help someone:
```dart
@dao
abstract class DeviceDao {
  @Query('SELECT * FROM DeviceEntity WHERE id = :id')
  Future<DeviceEntity> findBy(String id);

  @delete
  Future<void> remove(DeviceEntity entity);

  Future<void> removeById(String id) {
    return findBy(id).then(remove);
  }
}
```
And use it as:
```dart
await dao.removeById(reviceId);
```
