### ISSUE TITLE
Streams over single values do not emit null values

### ISSUE THREAD

**Issue by mqus** [vitusortner/floor#338]
As mentioned in #320, Streams over a single value like the one in the following example do not update if it returns no result:
```dart
@Query('SELECT * FROM Person WHERE id = :id')
Stream<Person> findPersonById(int id);
```
So if the person with the matching id is deleted, the Stream will re-execute the query but will not propagate the null result. 
As this is this way to emulate Rooms behaviour then there are three actions we can take (and I think we should take at least one of them):
1. Document the current behaviour (streams over single events only appear in examples but not in the section about streams
2. Add an option to the `@Query` annotation which enables null propagation/emission
3. Emit null values by default.

Currently I'm leaning towards 1+2 for having backwards compatibility and the option to return empty entries.

**Comment by vitusortner** [comment]
Your first point sounds great. I'll open a PR in a bit to add proper documentation. About the second and third, I would prefer to wait until Dart's non-nullable types arrive as the feature doesn't seem to be too urgent. This way, we can make use of the type system to infer if `null`s should be propagated. Nullable types will have to be marked with `?` whereas non-nullable types will stay the same.

What are your thoughts about this?

```dart
@Query('SELECT * FROM Person WHERE id = :id')
Stream<Person?> findPersonById(int id); // emits null when no person found

@Query('SELECT * FROM Person WHERE id = :id')
Stream<Person> findPersonById(int id); // never emits null
```
