### ISSUE TITLE
@MappedSuperclass

### ISSUE THREAD

**Issue by kosik** [vitusortner/floor#342]
Hibernate ORM as good as javax.persistence package provides handy inheritance strategy. You can extend your class with parent @MappedSuperclass and keep/separate common properties in-table or out-table.

Catch one eye here, how coll it might work: 

@MappedSuperclass 
public class BaseEntity implements Serializable {
    
    @Basic(optional = false)
    @Column(name = "create_time_stamp", nullable = false, length = 11, updatable = false)
    @JsonProperty("timeStamp")
    private Long createTimeStamp;
    
    private  Long updateTime;

Whether it is possible to implement something similar with Floor ?

**Comment by mqus** [comment]
I must confess that I don't really know how MappedSuperclass works but you can let classes marked with `@entity` or `@DatabaseView` extend baseclasses which contain common fields. They are then treated by floor as if they are a field of the entity class. You won't have to annotate the base class itself and you can annotate the fields there like the fields in a regular entity if needed.

An example and an explanation for inheritance of entities/views is currently missing in the README, I'll try to add that asap.

**Comment by mqus** [comment]
So I looked up `@MappedSuperclass` now and it is exactly like I described. You can use it in floor exactly like in JPA, only that you don't have to annotate the base class with `@MappedSuperclass`, it is included automatically.

**Comment by mqus** [comment]
This seems to be resolved, closing. Please reopen if you disagree :)
