### ISSUE TITLE
sqfliteDatabaseFactory returns object

### ISSUE THREAD

**Issue by hsul4n** [vitusortner/floor#345]
Getting syntax error `The method 'getDatabasePath' isn't defined for the type 'Object'` because 
`sqfliteDatabaseFactory` returns `Object` instead of `DatabaseFactory`.

https://github.com/vitusortner/floor/blob/5dd32c3b5cecbb16205d54145f736befbb371253/floor/lib/src/sqflite_database_factory.dart#L8

**Comment by vitusortner** [comment]
Did you run flutter pub get already? This functionality has been introduced with the lastest release which makes the library depend on a new package.

**Comment by hsul4n** [comment]
> Did you run flutter pub get already? This functionality has been introduced with the lastest release which makes the library depend on a new package.

Yep, I've run `flutter pub get` already but still getting the same. also, I tried to upgrade SDK as same as in example `>=2.6.0 <3.0.0`,

Is there any future purpose that prevents passing return type as `DatabaseFactory`.

**Comment by mqus** [comment]
I also had that problem and my solution was running `pub upgrade` (with all caveats). I assume that we are giving a dependency range for a dependency which is too permissive on the lower end.

We might have to change 
https://github.com/vitusortner/floor/blob/0284749b276fd8e3eed1380159ca7a43009eb352/floor/pubspec.yaml#L14
to
`sqflite: ^1.3.0 `

But I don't know if that is everything that's necessary.
