### ISSUE TITLE
Can't compare fields against blank

### ISSUE THREAD

**Issue by jaumzera** [vitusortner/floor#352]
I'm not sure if its a Floor's issue, anyway I'm reporting here just to check.

Anytime I try to compare a field against blank (''), the generated comparison breaks the SQL. For instance:
```sql
select * from Customer c where c.city = '' and c.state = ?
```
The output is: 

```sql
select * from customer c where c.city = and c.state = 'PR'
```

**Comment by mqus** [comment]
Did you try to escape the `'` literals (`\'`)? It could be possible that dart detects `'abc''def'`as two appended strings with the combined value of `'abcdef'`
Could you write the complete line (including `@Query` and everything)?

**Comment by jaumzera** [comment]
Yes, I did.
The query I've mentioned above was only illustrative, the real query is a little bit more complex:
```java
@Query('''
      select f.* from Freight f 
      where f.enabled = 1 
        and lower(f.crop) = lower(:cropId)
        and f.regionChannel = :branchId
        and (f.product = :productExternalId 
            or f.segment = :productSegment 
            or (f.mixGroup = :productMixGroup and f.segment = '')
      order by 
        f.product desc, 
        f.segment desc, 
        f.mixGroup desc
      limit 1
  ''')
```
outputs: 
```java 
 'select f.* from Freight f where f.enabled = 1 and lower(f.crop) = lower(?) and f.regionChannel = ? and (f.product = ? or f.segment = ? or (f.mixGroup = ? and f.segment = '
        ') order by f.product desc, f.segment desc, f.mixGroup desc limit 1',
```

Scaping seems to has no effect:
```sql
or (f.mixGroup = :productMixGroup and f.segment = \'\')
```
The output is the same.

**Comment by mqus** [comment]
Thank you! I'll take a look.

**Comment by mqus** [comment]
Ok I think I found the issue, **floor** is not escaping `'` correctly, we just insert them as-is. I'll try to whip up a fix tomorrow. Here is the line that needs fixing:
https://github.com/vitusortner/floor/blob/0284749b276fd8e3eed1380159ca7a43009eb352/floor_generator/lib/writer/query_method_writer.dart#L129

**Comment by jaumzera** [comment]
Nice. 
A fixed it temporally using `length(f.segment) > 0`

**Comment by jaumzera** [comment]
Well, I don't know if it helps, but what I've just realized was when I use `length(f.segment) = 0` the output query is generated in a single line: 

```sql 
'select f.* from Freight f where f.enabled = 1 and lower(f.crop) = lower(?) and f.regionChannel = ? and (f.product = ? or f.segment = ? or (f.mixGroup = ? and length(f.segment) = 0)) order by f.product desc, f.segment desc, f.mixGroup desc limit 1'
```

So I think the point is somewhere berfore the line you commented. Maybe here: floor_generator/lib/processor/query_method_processor.dart:63

**Comment by mqus** [comment]
The single vs multiple line happens because tge code generator formats the code and will try to reduce line width by putting the second part (separated by `''`) on a separate line. When no `''` are there then it will not split the string and everything remains on the same line.
