### ISSUE TITLE
How to reset an in-memory database?

### ISSUE THREAD

**Issue by lucasmaffazioli** [vitusortner/floor#367]
I'm creating tests for my app and before every test I need to reset the database to its initial form, since I have autogenerated PK columns.

Currently I'm doing this:
`database = await $FloorAppDatabase.inMemoryDatabaseBuilder().build();`

But the database I get is the same that I had before. Is there a way I can do this?

**Comment by mqus** [comment]
The obvious workaround would be a dao function which drops all data... But we should definitely look into why the in-memory db is not a new one. I'll try later.

**Comment by mqus** [comment]
We also have integration tests, e.g. here:

https://github.com/vitusortner/floor/blob/6209163750ed80c6f3a8ecd0401f1d51fdcbd41b/floor/test/integration/blob/blob_test.dart#L12-L35

As you can see we're also using an `inMemoryDatabase` and everything works as expected. This is of course only a simple case, we also have [files with more than one test](https://github.com/vitusortner/floor/blob/develop/floor/test/integration/view/view_test.dart), everything works there, too.

So your use-case seems to be special(in the sense that it does not work :smile:). Could you share a bit more code if you still have problems, e.g. the important parts of your test?

**Comment by lucasmaffazioli** [comment]
Thanks for the response! Indeed, the tests of Floor really works. 

I think is not a bug of Floor, so if you don't think this problem is related to this awesome plugin, please close the issue. Thanks.



I'm using GetIt and even tho the build method is called, the DB is the same.

```

GetIt locator = GetIt.instance;

const bool USE_TEST_IMPLEMENTATION = true;

void setupLocator() {
  locator.registerLazySingleton<LocatorDatabase>(() => LocatorDatabase());
}

void main(){
    setUp(() {
      setupLocator();
    });

    tearDown(() {
      locator.reset();
    });

   // my tests
}


class LocatorDatabase {
  bool _isInstanciated = false;
  AppDatabase _database;

  Future<AppDatabase> getDatabase() async {
    if (!_isInstanciated) {
      if (USE_TEST_IMPLEMENTATION) {
        _database = await $FloorAppDatabase.inMemoryDatabaseBuilder().build();
        List<dynamic> a = await _database.database.rawQuery('SELECT * FROM approach');
        //
        print('db created');
        a.forEach((e) {
          print(e);
        });
      } else {
        _database = await $FloorAppDatabase
            .databaseBuilder('app_database.db')
            .addCallback(callback)
            .build();
      }
      _isInstanciated = true;
    }
    return _database;
  }
}

```

Here's my output:

> db created
> {id: 2, name: Harry Potter}
> {id: 3, name: Joana Dark}

**Comment by mqus** [comment]
This really doesn't look like a bug on our side, but I also can't make out why it would not work in your case.
But I'm not 100% sure. Do you have a minimal example which reproduces the behaviour? If not I can try to reproduce it myself but it might take a bit longer.

**Comment by mqus** [comment]
I noticed a difference: our integration tests close the database afterwards, your code snippet doesn't seem to do that.

**Comment by lucasmaffazioli** [comment]
Yeah it was that easy. hahaha... I thought the act of resetting get_it, and consequently the object that had the DB would re-create from 0.

Thanks a lot for your work on the plugin and your help!
