### ISSUE TITLE
autoGenerate not working  - @PrimaryKey(autoGenerate: true)

### ISSUE THREAD

**Issue by amila4d** [vitusortner/floor#368]
When I insert object to the database it will giving unique constraint error. I have passed o and null for auto increment ID. But it is not success. I have to give manual increment number to save object data to database.

**Comment by mqus** [comment]
Hi and thanks for reporting! 

I was actually not sure if this works, so I wrote an integration test: https://github.com/vitusortner/floor/blob/issue/test-%23368-autoincrement/floor/test/integration/autoincrement/autoinc_test.dart

This test runs through successfully though (with the id set to `null` before inserting it), so I assume that there is another issue with your code. Could you post the relevant source code bits(your entity and your DAO) so we could take a look?

**Comment by vitusortner** [comment]
I'm closing this issue as the origin of the problem remains unclear.
