### ISSUE TITLE
Question: Which is the best approach to update stream when new records are inserted

### ISSUE THREAD

**Issue by cassioseffrin** [vitusortner/floor#372]
I am facing a situation in a StreamBuilder that holds a List of Objects from sqlite. That List<Object> is a Stream from floor DAO.  What I am trying to achieve is something like is made in firebase. The firebase emit new values to stream when they are inserted, in case of sqlite the values comes from a SELECT. My first idea was create a trigger that notify the bloc about the new record inserted and then just sink.add it to the stream<List<Object>>.  However something tell me that I am reinventing the wheel, I'll appreciate if someone could share some experience about it.

**Comment by mqus** [comment]
Currently, streams *are* already triggered by dao methods which `@insert`, delete or update. But those streams contain the whole updated table, not just the changed records, so if I understand you correctly then you only want to see what changed, right?(let's call it a diff). 

This should be achievable by making a middleman which recieves the stream update from floor, compares it to the previous version, puts this diff into its output and saves the current stream output for the next update. I don't have code for this ready but it should be doable. Alternatively you could wrap your DAO and take the inserted entities from the source.

**Comment by cassioseffrin** [comment]
> Currently, streams _are_ already triggered by dao methods which `@insert`, delete or update. But those streams contain the whole updated table, not just the changed records, so if I understand you correctly then you only want to see what changed, right?(let's call it a diff).
That sounds very good @mqus (streams _are_ already triggered by dao)! I don't have reached the point where my middleware will sync the sqlite database with the REST API. May the streams from "floor DAO" will  do all the work for me. I still haven't tested if the whole lists of stream will not impact in slow updates. I will need to test it, however I suspect even adding just one item in stream the whole list is rebuild on the screen anyway, in that case getting the whole list from dao may will not be so bad. Just the final tests will capable to answer the performance points of my question. Anyway I have appreciate your expertise.

As the question was answered, I think I can close this question for now, when I got the final results of performance analysis  I will post here, may it take a time cause it's a future task in my sprint. Thks again @mqus, I have using floor since the beginning and both the evolution and stability are making the right choice for persistence layer. Thks!
