### ISSUE TITLE
Generated method without return statement

### ISSUE THREAD

**Issue by jaumzera** [vitusortner/floor#379]
I have the following method in a class called `SimulationDao` to save a simulation and its items: 

```
@transaction
  Future<int> saveWithItems(SimulationEntity simulation) async {
    final savedId = await this.save(simulation);
    simulation.id = savedId;
    simulation.items.forEach((element) => element.simulationId = savedId);
    DaoFactory.instance.simulationItemDao.saveAll(simulation.items);
    return savedId;
  }
```

But the generated method has no return statement: 
```
  @override
  Future<int> saveWithItems(SimulationEntity simulation) async {
    if (database is sqflite.Transaction) {
      await super.saveWithItems(simulation); 
    } else {
      await (database as sqflite.Database)
          .transaction<void>((transaction) async {
        final transactionDatabase = _$AppDatabase(changeListener)
          ..database = transaction;
        await transactionDatabase.simulationDao.saveWithItems(simulation);
      });
    }
  }
```

**Comment by mqus** [comment]
Your're right, this is a bug.

**Comment by mqus** [comment]
Oh I have to correct myself: this is not exactly a bug, since this is a documented limitation:

> Whenever you want to perform some operations in a transaction you have to add the @transaction annotation to the method. It's also required to add the async modifier. These methods can only return Future<void>.

Depending on the way you look at it, this could be a bug since it didn't report an error. But currently I don't see why transactions couldn't return values.
