### ISSUE TITLE
Question: Dynamic query, Criteria Builder or Elasticsearch

### ISSUE THREAD

**Issue by cassioseffrin** [vitusortner/floor#384]
Hello Guys,

I am developing a complex filter screen where I have multiples fields that must be combined to perform the query with pagination (limit and offset). In my particular case I cannot get the entire list and work with stream transform due the fact my List<Entity> is paginated.

Floor has any alternative like  pass the entire query (dynamic query) to the dao instead just field parameters? Or something like criteria builder or may elastic search?

**Comment by mqus** [comment]
You can use sqflite directly (via `$FloorMyDatabase.database.rawQuery()`, see below), but apart from that this is pretty much what #315 tries to implement (some kind of raw query which is *not* parsed and checked and uses simple string replacements for the arguments)

Using a raw query right now:
```dart
AppDatabase _database = await $FloorAppDatabase.databaseBuilder('myDb.db').build();
List<Map<String,dynamic>> output = await _database.database.rawQuery(
    'SELECT * FROM Page LIMIT $count OFFSET $offset'
  )
print(output);
```

**Comment by cassioseffrin** [comment]
@mqus the simples raw queries have worked, thank you! I am closing this question.
