### ISSUE TITLE
Undefinde TestDatabase class

### ISSUE THREAD

**Issue by sinhphan** [vitusortner/floor#390]
![image](https://user-images.githubusercontent.com/1941392/90119305-59d12b00-dd94-11ea-8785-0dbd952c6447.png)

**Comment by mqus** [comment]
DISCLAIMER: Badly formulated issues make me angry and will make me rant. Do not read the following if you want a civil and reasonable discussion.

> Do you expect me to teach you Dart? This is not a helpdesk for dart issues! What is this screenshot (a screenshot and not even a code snippet? wtf?) The error message tells you exactly what is wrong: you *have not defined a class named "TestDatabase"*. I'm speechless. Even a badly (machine-)translated explanation will help more than your low-effort post. Now that I look even more, there is not a hint of floor in this code. The first line even tells you: "floor is *unused*" What makes you think that this is the right place to get help or even think that this is an issue of floor?
/rant

Sorry that you are the specific person to get that pent-up anger. Your contribution is appreciated but *please* make it easier for us to help you. Just try to imagine: If you would get as much information as you see above: would you be able to help, and in the context of this specific package: would you *want* to help?
Now, to your problem. Please provide a minimal code example that reproduces your issue. You can post code in github by using
```md
    ```dart
    your.dart.code(here);
    ```
```
Please also explain what you were doing. What did you try to achieve? What have you already tried, what went wrong?

More specific: where is `TestDatabase` defined? Maybe you wanted to do 
```dart
group('database test', () {
  MyAppDatabase testDatabase;
});
```
(replace `MyAppDatabase` with the actual name of the class defined in `data/database.dart`)

**Comment by sinhphan** [comment]
thank
