### ISSUE TITLE
How can I use a data type parameter in the query function on the floor?

### ISSUE THREAD

**Issue by claudneysessa** [vitusortner/floor#393]
How can I use a data type parameter in the query function on the floor?

**Comment by claudneysessa** [comment]
Example:


  @Query("""
    SELECT Coleta.*, 
           ( select sum(ItemColeta.PD_QTD) 
               from ItemColeta 
              where ItemColeta.MCO_COD = Coleta.MCO_COD 
           ) as MCO_TOTAL
      FROM Coleta
     WHERE MCO_DTAGENDA <= :data
       and MCO_STATUS = :status
  ORDER BY MCO_DTCOLETA
  """)
  Future<List<ColetaEntity>> findStatusDataMenor(int status, String data);

**Comment by claudneysessa** [comment]
Você quis dizer: Este código a cima não funciona, porém se eu colocar direto o valor funciona
75/5000
This code above does not work, but if I put it directly the value works

@query("""
SELECT Coleta.*,
( select sum(ItemColeta.PD_QTD)
from ItemColeta
where ItemColeta.MCO_COD = Coleta.MCO_COD
) as MCO_TOTAL
FROM Coleta
WHERE MCO_DTAGENDA <= "2020-08-01"
and MCO_STATUS = :status
ORDER BY MCO_DTCOLETA
""")
Future<List> findStatusDataMenor(int status);

**Comment by mqus** [comment]
Please elaborate. What do you mean with "does not work"? Do you get an error message?
Another thing I notice in your case: we currently only support parameters being referenced in the same order as they're specified in the function(#224). This is being worked on in #361. So the first example might work if you use
```dart
@query("""
SELECT Coleta.*,
( select sum(ItemColeta.PD_QTD)
from ItemColeta
where ItemColeta.MCO_COD = Coleta.MCO_COD
) as MCO_TOTAL
FROM Coleta
WHERE MCO_DTAGENDA <= :data
and MCO_STATUS = :status
ORDER BY MCO_DTCOLETA
""")
Future<List> findStatusDataMenor(String data, int status);
```

(Btw, the `Future<List>` bit is also not correct but I assume that you are just omitting the details here)

**Comment by claudneysessa** [comment]
Thanks for the guidance I didn't pay attention to the order of the parameters and this was the problem, thank you very much!

**Comment by claudneysessa** [comment]
> Please elaborate. What do you mean with "does not work"? Do you get an error message?
> I noticed one thing in your example though: we currently only support parameters being referenced in the same order as they're specified in the function(#224). This is being worked on in #361. So the first example might work if you use
> 
> ```dart
> @query("""
> SELECT Coleta.*,
> ( select sum(ItemColeta.PD_QTD)
> from ItemColeta
> where ItemColeta.MCO_COD = Coleta.MCO_COD
> ) as MCO_TOTAL
> FROM Coleta
> WHERE MCO_DTAGENDA <= :data
> and MCO_STATUS = :status
> ORDER BY MCO_DTCOLETA
> """)
> Future<List> findStatusDataMenor(String data, int status);
> ```
> 
> (Btw, the `Future<List>` bit is also not correct but I assume that you are just omitting the details here)

Thanks for the guidance I didn't pay attention to the order of the parameters and this was the problem, thank you very much!

**Comment by claudneysessa** [comment]
Solved!
