### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by rahuljidgedev** [vitusortner/floor#396]
Below is the logs when I run <B>flutter packages pub run build_runner build</B> command output:

[INFO] Starting Build

[INFO] Updating asset graph...
[INFO] Updating asset graph completed, took 2ms

[INFO] Running build...
[SEVERE] floor_generator:floor_generator on lib/database.dart:

Failed assertion: boolean expression must not be null
[INFO] Running build completed, took 58ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 7ms

[SEVERE] Failed after 69ms

The runner is failing to create the "database.g.dart" file. It shows the above error.
I'm using Ubuntu OS.

Following is the pubspec.yml file dependencies:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  floor: ^0.14.0
  logger: ^0.9.2
  speech_recognition: ^0.3.0
  intl: ^0.16.1
  permission_handler: ^5.0.1+1
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  functional_widget_annotation: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.14.0
  build_runner: ^1.7.3

dependency_overrides:
  analyzer: '0.40.2'

=> Following is my folder structure:
- /lib/databse.dart
- /lib/dao/ListItemDao.dart
-/lib/entity/ListItem.dart

=> database.dart

// required package imports
import 'dart:async';
import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

import 'dao/ListItemDao.dart';
import 'entity/ListItem.dart';

part 'database.g.dart';

@Database(version: 1, entities: [ListItem])
abstract class AppDatabase extends FloorDatabase {
  ListItemDao get listItemDao;
}

=> ListItem.dart

@entity
class ListItem {
  @PrimaryKey(autoGenerate: true)
  int id;
  final String speechText, timeStamp;
  final bool textOnUserLeft;

  ListItem(this.speechText, this.textOnUserLeft, this.timeStamp);
}

=> ListItemDao.dart

@dao
abstract class ListItemDao {
  /*@Query('select * from ListItem')
  Future<List<ListItem>> getAllSpeech();*/

  /*@Query('select count(*) from ListItem')
  Future<int> getSpeechCount();*/

  /*@Query('select * from ListItem')
  Stream<List<ListItem>> getAllSpeechStream();*/

  @insert
  Future<void> insertSpeakItem(ListItem listItem);
}

If I comment out all methods only in the ListItemDao file, the build runner successfully creates "database.g.dart" file. 
If I uncomment any one method build runner gives  <B>Failed assertion: boolean expression must not be null.</B> error.

Below is build runner error with verbose:

[  +69 ms] executing: [/home/ekalpa/Android/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +16 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 81a45ec2e5f80fa71d5135f1702ce540558b416d
[        ] executing: [/home/ekalpa/Android/flutter/] git tag --contains HEAD
[ +114 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.21.0-9.2.pre
[   +6 ms] executing: [/home/ekalpa/Android/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/ekalpa/Android/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +24 ms] executing: [/home/ekalpa/Android/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +24 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +16 ms] Using /home/ekalpa/Android/flutter/.pub-cache for the pub cache.
[        ] executing: /home/ekalpa/Android/flutter/bin/cache/dart-sdk/bin/pub run build_runner watch -v
[INFO] Generating build script...
[INFO] Generating build script completed, took 225ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 8.2s

[INFO] Watch:Setting up file watchers...
[INFO] Watch:Setting up file watchers completed, took 8ms

[INFO] Watch:Waiting for all file watchers to be ready...
[INFO] Watch:Waiting for all file watchers to be ready completed, took 48ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Building new asset graph...
[INFO] BuildDefinition:Building new asset graph completed, took 829ms

[INFO] BuildDefinition:Checking for unexpected pre-existing outputs....
[INFO] BuildDefinition:Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Build:Running build...
[INFO] build_resolvers:Generating SDK summary...
[INFO] Heartbeat:2.1s elapsed, 0/16 actions completed.
[INFO] build_resolvers:Generating SDK summary completed, took 2.1s

[FINE] floor_generator:floor_generator on lib/screens/home/widgets/MenuConstants.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/utils/AppConstants.dart:Running FloorGenerator
[INFO] Heartbeat:4.1s elapsed, 2/17 actions completed.
[INFO] Heartbeat:5.1s elapsed, 2/17 actions completed.
[INFO] Heartbeat:6.2s elapsed, 2/17 actions completed.
[INFO] Heartbeat:7.3s elapsed, 2/17 actions completed.
[INFO] Heartbeat:8.5s elapsed, 2/17 actions completed.
[INFO] Heartbeat:9.7s elapsed, 2/17 actions completed.
[INFO] Heartbeat:10.9s elapsed, 2/17 actions completed.
[INFO] Heartbeat:12.6s elapsed, 2/17 actions completed.
[FINE] floor_generator:floor_generator on lib/screens/Routes.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/main.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/screens/home/Home.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/screens/home/widgets/CardWidget.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/screens/tutorial/Tutorial.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/screens/home/widgets/MenuWidget.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/screens/starredMessages/StarredMessages.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/screens/about/About.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/screens/feedback/UserFeedback.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/utils/ThreadShapeBorder.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/generated_plugin_registrant.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/database.dart:Running FloorGenerator
[SEVERE] floor_generator:floor_generator on lib/database.dart:

Failed assertion: boolean expression must not be null
package:analyzer/src/dart/element/display_string_builder.dart 250:9      ElementDisplayStringBuilder._writeNullability
package:analyzer/src/dart/element/display_string_builder.dart 151:5      ElementDisplayStringBuilder.writeInterfaceType
package:analyzer/src/dart/element/type.dart 840:13                       InterfaceTypeImpl.appendTo
package:analyzer/src/dart/element/type.dart 1696:5                       TypeImpl.getDisplayString
package:floor_generator/misc/change_method_processor_helper.dart 54:36   ChangeMethodProcessorHelper.getEntity.<fn>
dart:collection                                                          ListMixin.firstWhere
package:floor_generator/misc/change_method_processor_helper.dart 51:22   ChangeMethodProcessorHelper.getEntity
package:floor_generator/processor/insertion_method_processor.dart 56:28  InsertionMethodProcessor.process
package:floor_generator/processor/dao_processor.dart 91:70               DaoProcessor._getInsertionMethods.<fn>
dart:core                                                                Iterable.toList
package:floor_generator/processor/dao_processor.dart 92:10               DaoProcessor._getInsertionMethods
package:floor_generator/processor/dao_processor.dart 53:30               DaoProcessor.process
package:floor_generator/processor/database_processor.dart 75:9           DatabaseProcessor._getDaoGetters.<fn>
dart:core                                                                Iterable.toList
package:floor_generator/processor/database_processor.dart 78:8           DatabaseProcessor._getDaoGetters
package:floor_generator/processor/database_processor.dart 33:24          DatabaseProcessor.process
package:floor_generator/generator.dart 57:44                             FloorGenerator._getDatabase
package:floor_generator/generator.dart 24:22                             FloorGenerator.generateForAnnotatedElement
package:source_gen/src/generator_for_annotation.dart 53:30               GeneratorForAnnotation.generate
package:source_gen/src/builder.dart 301:33                               _generate
package:source_gen/src/builder.dart 79:15                                _Builder._generateForLibrary
package:source_gen/src/builder.dart 71:11                                _Builder.build
package:build                                                            runBuilder
package:build_runner_core/src/generate/build_impl.dart 485:19            _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15   _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 483:23            _SingleBuild._runForInput.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                   _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                    NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 440:22            _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                            Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 436:17            _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 374:38            _SingleBuild._runBuilder.<fn>
dart:async                                                               Future.wait
package:build_runner_core/src/generate/build_impl.dart 373:36            _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 319:20            _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                               _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                   _SingleBuild._matchingPrimaryInputs

[FINE] floor_generator:floor_generator on lib/dao/ListItemDao.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on lib/entity/ListItem.dart:Running FloorGenerator
[FINE] floor_generator:floor_generator on test/widget_test.dart:Running FloorGenerator
[INFO] Build:Running build completed, took 16.7s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 29ms

[SEVERE] Build:
Failed after 16.8s

**Comment by mqus** [comment]
On a quick first skim this looks like an issue with floors dependencies... I'll try to look into it more tomorrow or the day after.

**Comment by rahuljidgedev** [comment]
@mqus, Thanks.  Yes. please take a look at it.  However, I've managed to fix the issue after debugging the dependencies.

The error is gone after I removed the following code from the pubspec.yml file:
<B>dependency_overrides:
analyzer: '0.40.2'</B>

I feel we must look for: <I>why is this behavior on adding the <b>analyzer: '0.40.2'</b> above dependency_overriedes.</I>

**Comment by aarajput** [comment]
I am facing same issue. 
Any update?

**Comment by vitusortner** [comment]
Are you still facing this probelm?

**Comment by mqus** [comment]
This issue seems to be solved (probably by updating the dependencies and the nullsafety migration), so I'll be closing this issue. If you do encounter this problem again, please open a new issue or reopen this one :)
