### ISSUE TITLE
Which version is planned to support fts

### ISSUE THREAD

**Issue by jiechic** [vitusortner/floor#397]
We use a room that supports fts on the native development of android. We hope to be able to migrate to flutter. Look for a flutter package similar to room on flutter. We found you
We would like to ask if there are plans to support fts

**Comment by mqus** [comment]
Could you please expand on what fts is? It doesn't ring a bell immediately for me, sorry :)

And following that, since we are not room, you could also describe what you feel is missing from rooms fts feature(if that is possible) or what could be better. Maybe we could expand on that.

**Comment by mqus** [comment]
So I actually looked it up now (should have done that before commenting, sry) and fts(full text search) is an optional sqlite module. 

Afaict, this situation is the same as with the json extension: sqflite(our sqlite database driver) does not support it, so we also can't support it right now. I'm also not sure where the issue is(if this is already supported for all platforms that sqflite supports or if e.g. iOS does not include the module)

**Comment by jiechic** [comment]
In the [official sqlite documentation](https://www.sqlite.org/fts3.html),
`FTS4 is an enhancement to FTS3. FTS3 has been available since SQLite version 3.5.0 (2007-09-04) The enhancements for FTS4 were added with SQLite version 3.7.4 (2010-12-07).`

on Android:
I found the [official document of android](https://developer.android.com/reference/android/database/sqlite/package-summary.html)
since android 11 was beging sqlite version 3.7，I see [test record](https://stackoverflow.com/questions/2421189/version-of-sqlite-used-in-android/4377116#4377116) since android 11 has beging sqlite version 3.7.4

on iOS
i dont't found Any information on official document
i found [test record](https://github.com/yapstudios/YapDatabase/wiki/SQLite-version-(bundled-with-OS)) for get some information
since iOS 5.1.1 is beging sqlite version 3.7.7

i found sqflite minversion is android 16 and iOS 8
so，sqflite is support fts3 and fts4，but sqflite don't support fts5 on all android or ios version ，you can see issue in [sqflite](https://github.com/tekartik/sqflite/issues/105)

Can you consider adding support for fts3 and fts4 like room？
[room fts3](https://developer.android.com/reference/androidx/room/Fts3)
[room fts4](https://developer.android.com/reference/androidx/room/Fts4)

**Comment by jiechic** [comment]
and i see dart office package [sqlite3](https://pub.dev/packages/sqlite3) has new version for sqlite，i can support fts3、 fts4、fts5 on any platforms but not only android ，ios
this is only Suggest for floor update sqlite that has unified characteristics

**Comment by jiechic** [comment]
have any plan for this？

**Comment by jiechic** [comment]
I send a pull request #407 for support this
