### ISSUE TITLE
List<String> query parameter not being used in _queryAdapter.queryListStream()

### ISSUE THREAD

**Issue by ericomine** [vitusortner/floor#410]
I want to create a query which receives a List<String> as a parameter (in the example below it's the 3rd parameter). The result I get when I run build_runner is this:

```
// This is a simplified version of what I'm trying to do
Stream<List<AnimalData>> watchAnimals(
      String pattern, bool anyCategory, List<String> categories, int offset) {
    final valueList1 = categories.map((value) => "'$value'").join(', ');
    return _queryAdapter.queryListStream(
        'SELECT * FROM Animals WHERE identifier LIKE ? AND (CASE WHEN ? IS FALSE THEN category IN(?) END) LIMIT 20 OFFSET ?',
        arguments: <dynamic>[
          pattern,
          anyCategory == null ? null : (anyCategory ? 1 : 0),
          offset
        ],
```

So it seems that Floor converted the list into a single String with commas, but the resulting valueList1 has not been passed into the _queryAdapter.queryListStream() call. During execution, I get a wrapDatabaseException.

Is this a bug?
I thought it should work, as it is very similar to this example from the docs:

```
@Query('SELECT * FROM Person WHERE id IN (:ids)')
Future<List<Person>> findPersonsWithIds(List<int> ids); 
```

**Comment by vitusortner** [comment]
Hi! Something, indeed, seems to be off here. Can you provide some more information about your DAO method `watchAnimals()` by copy-pasting its definition?

**Comment by ericomine** [comment]
I'm sorry for the delay. 

Is the list only supposed to work when it's the last argument in the query?

I'd defined the method as below:
`@Query('''
SELECT * FROM Animals
WHERE identifier LIKE :pattern
AND (CASE WHEN :anyCategory IS FALSE THEN category IN(:categories) END)
LIMIT 20 OFFSET :offset''')
Stream<List<AnimalData>> watchAnimals(String pattern, bool anyCategory, List<String> categories, int offset)`

I've used a workaround to solve my problem, instead of passing the List<String>, I've concatenated them and and used INSTR instead of IN in the query.

**Comment by istornz** [comment]
Exactly same issue here :/

**Comment by istornz** [comment]
Ok so I found the problem !

I missed a space between ```IN``` and the ```(```.
So this **NOT** work : ```IN(:ids)```
This **WORK**: ```IN (:ids)```

I think you can close the issue :)

**Comment by vitusortner** [comment]
@istornz thanks for informing us about the resolution of your problem. I think we should make queries using `IN` be more tolerant as `IN` without a space before the opening parenthesis should work as well. I'll have a look!
