### ISSUE TITLE
Is there a way to add unique constraint to the column??

### ISSUE THREAD

**Issue by DayDreamer-commits** [vitusortner/floor#420]
I need to add unique constraint while inserting a object, but i am not getting a way to do this.

**Comment by cassioseffrin** [comment]
@DayDreamer-commits Look at https://github.com/vitusortner/floor/issues/419#issue-726771083

@Entity(
  tableName: 'my_table',
  indices: [
    Index(value: ['email'], unique: true)
  ],
)

**Comment by DayDreamer-commits** [comment]
thanks a lot.
