### ISSUE TITLE
Is it support saveOrUpdate

### ISSUE THREAD

**Issue by onlycyndi** [vitusortner/floor#422]
Hi, thanks for this library.

Like title says , I want to update data when insert a new list which contain a little exist items

**Comment by mqus** [comment]
You might want to try `@Insert(onConflict: replace)` instead of `@insert` for your DAO function. This will effectively "update" the existing items in the database, since it replaces them.

**Comment by onlycyndi** [comment]
Thanks for you help, I have tried for this, and use the index `Index(value: ['xxx'], unique: true)`, it works.
