### ISSUE TITLE
How to use table name parameters when querying

### ISSUE THREAD

**Issue by islinjj** [vitusortner/floor#425]
I want to query by passing in the table name parameter
`@Query('SELECT * FROM :tableName')  
  Future<List<T>> findAllPersons(String tableName);
`
but, It can't work,
`(1) near "?": syntax error in "SELECT * FROM ?"
E/flutter ( 7614): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DatabaseException(near "?": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM ?) sql 'SELECT * FROM ?' args [Person]}`

How to deal?

**Comment by mqus** [comment]
To prevent sql injections, we use the internal mechanism of sqlite to assign values to variables. But this also means that it can only replace expressions, not table or column references, no keywords and especially not whole parts of queries.

**Comment by islinjj** [comment]
But I want to further encapsulate the select api so that developers can call it more conveniently, like this

`
@dao
abstract class PersonDao extends AbstractDao<Person> {}

abstract class AbstractDao<T> {
  @insert
  Future<void> insertItem(T item);
  @Query('....')
  Future<T> findById(int id);
}

`
What should I do? How should some query conditions be packaged?

**Comment by islinjj** [comment]
I solved it by calling the native sqlite method.

**Comment by salvaterra** [comment]
Try this.....


```
abstract class GenericDao<T> {

  @insert
  Future<void> insertObj(T obj);

  @insert
  Future<void> insertObjs(List<T> objs);

  @update
  Future<void> updateObj(T obj);

  @update
  Future<void> updateObjs(List<T> objs);

  @delete
  Future<void> deleteObj(T obj);

  @delete
  Future<void> deleteObjs(List<T> objs);

  @Query('SELECT * FROM \$DB_TABLE WHERE id = :id')
  Future<T> findObjById(int id);

  @Query('SELECT * FROM \$DB_TABLE')
  Future<List<T>> findAllObjs();

  @Query('SELECT * FROM \$DB_TABLE')
  Stream<List<T>> findAllObjsAsStream();
}

@dao
abstract class CatDao extends GenericDao<Cat>{
  String DB_TABLE = 'Cat';
}

```
