### ISSUE TITLE
how can I add table in  already existed db

### ISSUE THREAD

**Issue by TangYuanHuan** [vitusortner/floor#430]
I  want add a new table  in already existed db
I  do that 
1.
@JsonSerializable()
@Entity(tableName: 'test_db_model',primaryKeys: ['id'])
class TestDbModel {}

2. increase db version =>version: 4

3. add   TestDbDao get testDbDao;

4. add Migration 
Migration get migrate3To4 {
  return Migration(3, 4, (sqflite.Database database) async {
    printLog('migrate3To4:${await database.getVersion()}');
  });
}

5.trigger the code generator again

but I can not receive the desired effect

DatabaseException(no such table: test_db_model (code 1): , while compiling: INSERT OR REPLACE INTO test_db_model (id, text) VALUES (?, NULL)) sql 'INSERT OR REPLACE INTO test_db_model (id, text) VALUES (?, NULL)' args [1605608568191]}
20

**Comment by Jungle68** [comment]
me too.

**Comment by vitusortner** [comment]
Hello! The migration must be capable of creating your newly-added table. You'd usually use something along the lines of the following snippet. I'll extend the project's documentation to make this clearer. Do you have further questions?

```sql
CREATE TABLE `test_db_model` (
  `id` INTEGER PRIMARY KEY,
  `text` TEXT
)
```

**Comment by donpaul120** [comment]
I

> Hello! The migration must be capable of creating your newly-added table. You'd usually use something along the lines of the following snippet. I'll extend the project's documentation to make this clearer. Do you have further questions?
> 
> ```sql
> CREATE TABLE `test_db_model` (
>   `id` INTEGER PRIMARY KEY,
>   `text` TEXT
> )
> ```

Apologies, but I don't think this is sufficient, having to write SQL for every newly added model especially in development environment.. this is time consuming.
