### ISSUE TITLE
TypeConverter sample code with possible error 

### ISSUE THREAD

**Issue by cassioseffrin** [vitusortner/floor#439]
When the database final attribute has null value the DateTimeConverter will throws an error when it's convert a null value.

So I have made a correction with try catch to avoid it. May you could update the example on README.md. 

```
class DateTimeConverter extends TypeConverter<DateTime, int> {
  @override
  DateTime decode(int databaseValue) {
    try {
      return DateTime.fromMillisecondsSinceEpoch(databaseValue);
    } catch (e) {
      return null;
    }
  }

  @override
  int encode(DateTime value) {
    try {
      return value.millisecondsSinceEpoch;
    } catch (e) {
      return null;
    }
  }
}
```

**Comment by cassioseffrin** [comment]
The code above was my fix to documentation, it will be nice to update the docs to help the community. As I got no response from team I am closing it.

**Comment by vitusortner** [comment]
@cassioseffrin sorry for the late reply. Feel free to open a PR to improve the project's documentation.

**Comment by cassioseffrin** [comment]
Ok @vitusortner please check the PR:  https://github.com/cassioseffrin/floor/pull/1 . I am not sure I have made it in correct branch.

**Comment by cassioseffrin** [comment]
@vitusortner  I have made the PR, please check it here https://github.com/vitusortner/floor/pull/442

Thks!
