### ISSUE TITLE
Return last inserted ID/s

### ISSUE THREAD

**Issue by vitusortner** [vitusortner/floor#44]
Whenever inserting objects open up the possibility to return the inserted ID or IDs in case a list is getting inserted.
Investigate what Room returns on update and delete and decide if support these as well.

- [x] Insert
- [x] Update
- [x] Delete

**Comment by cassioseffrin** [comment]
This feature is already available in last version 0.12.0? If yes, how can I perform it?

**Comment by mqus** [comment]
theoretically you can use `Future<int>` or `Future<List<int>>` as a return type for `@insert` DAO functions, e.g. 
```dart
@insert
Future<List<int>> insertPersons(List<Person> person);
```
will return a list of primary ids which were generated and used by sqlite.
Of course, this will only work if your primary key is of type integer, but I think that only integer primary keys can be generated anyway. The `id`(or whatever you named it) field of those `Person` objects will not have changed, you would have to do that yourself if you want.

**Comment by cassioseffrin** [comment]
@mqus It's working in 0.12.0. Thks!

I have tested in previous version. In the previous version if I am not wrong the returned int value was 0 or 1 (true or false), just to represent if the insert/update were done/committed without errors. Now it's pretty better providing the accuracy ID information. Amazing feature and thks again!

**Comment by mqus** [comment]
In the case of `@update` and `@delete` it will return the count of changed rows, not the id. This `last inserted ID` in this ticket only applies to `@insert`. And as the (admittedly short) issue description says is 
> Investigate what Room returns on update and delete and decide if support these as well.

And this is (at least from my PoV) the amount of rows that were changed by the operation, just like the titles of the referenced PRs indicate. 

If you want the id of your updated row(s), look inside the id field of the Entity you provided to the update function, as this will not be changed(in the db and in your app) by either update nor delete operations.

**Comment by cassioseffrin** [comment]
@mqus   ok, it was very clear. Really this way similar to Room got better, thks!

**Comment by mqus** [comment]
And honestly, if you had read the README link I gave you, this would have been obvious:

> @update marks a method as an update method. When using the capitalized @Update you can specify a conflict strategy. Else it just defaults to aborting the update. These methods can return a Future of either void or int.

 >   void return nothing
 >   int return number of changed rows

>@delete marks a method as a deletion method. These methods can return a Future of either void or int.

>    void return nothing
>    int return number of deleted rows

**Comment by cassioseffrin** [comment]
Yeap indeed. I didn't understand correctly.  It's very clear in docs!
