### ISSUE TITLE
Update specific column of table  

### ISSUE THREAD

**Issue by UzairSun93** [vitusortner/floor#448]
Can anyone guide me how can i update the specific column or field of table because currently i am unable to update fields using this code?

Here is my dao Query 

  @Query("UPDATE attachment SET status=:status WHERE taskId = :taskID")
  Future<void> updateStatusTask(int status, String taskID);

and below is my Entity or Model:

import 'dart:typed_data';
import 'package:floor/floor.dart';

@Entity(tableName: 'attachment')
class UploadFile {
  int jobId;
  int typeId;
  String file;
  @PrimaryKey(autoGenerate: true)
  int mobId;

  String expiryDate;
  String containerId;
  String fileName;

  Uint8List image;
  String taskId;
  int status; //0 ==process , 1==Completes 2==fails,

  UploadFile(
      {this.jobId,
      this.typeId,
      this.file,
      this.mobId,
      this.expiryDate,
      this.image,
      this.containerId,
      this.taskId,
      this.status});

  UploadFile.fromJson(Map<String, dynamic> json) {
    jobId = json['job_id'];
    typeId = json['type_id'];
    file = json['file'];
    mobId = json['mob_id'];
    containerId = json['container_id'];
    expiryDate = json['expiry_date'];
    fileName = json['file_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['job_id'] = this.jobId;
    data['type_id'] = this.typeId;
    data['file'] = this.file;
    data['mob_id'] = this.mobId;
    data['expiry_date'] = this.expiryDate;
    data['container_id'] = this.containerId;
    data['file_name'] = this.fileName;

    return data;
  }
}

**Comment by vitusortner** [comment]
Hi! What's the error you're getting? I suggest explicitly defining the return type of `updateStatusTask` as `Future<void>` or `Future<int>`, depending on your use case. More information can be found in the project's readme https://github.com/vitusortner/floor#data-changes.

**Comment by mqus** [comment]
if you use `Future<void>` your code should work like you wrote it. But as you did not follow-up we can't help you further :cry: . 

Due to inactivity I will close this issue. Feel free to reopen if you have any updates!.
