### ISSUE TITLE
The specified language version is too high.

### ISSUE THREAD

**Issue by tajaouart** [vitusortner/floor#464]
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0-nullsafety.3/lib/ascii.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.11.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
lib/dao/database.g.dart:59:18: Error: Type 'StreamController' not found.
  _$AppDatabase([StreamController<String> listener]) {
                 ^^^^^^^^^^^^^^^^

**Comment by vitusortner** [comment]
Which version of the library are you using? Also, can you provide your database.dart file?

**Comment by mqus** [comment]
I'll assume that this problem was solved, since you did not answer for so long. If you have any updates, feel free to reopen this issue or create a new one :)
