### ISSUE TITLE
windows flutter: MissingPluginException

### ISSUE THREAD

**Issue by LuckyJayce** [vitusortner/floor#474]
flutter: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160:7)
    flutter: <asynchronous suspension>
    flutter: #1      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:20)
    flutter: <asynchronous suspension>
    flutter: #2      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:20)
    flutter: <asynchronous suspension>
    flutter: #3      DatabaseFactoryExtension.getDatabasePath (package:floor/src/sqflite_database_factory.dart:29:17)
    flutter: <asynchronous suspension>
    flutter: #4      _$FlutterDatabaseBuilder.build (package:flutter_app/modules/main/model/db/database.g.dart:46:11)
    flutter: <asynchronous suspension>
    flutter: #5      DBManager.masterDatabase (package:flutter_app/modules/main/model/db/db_service_manager.dart:76:32)
    flutter: <asynchronous suspension>
    flutter: #6      ComposeDao.masterDao (package:flutter_app/modules/main/model/db/biz/base_service.dart:93:34)
    flutter: <asynchronous suspension>
    flutter: #7      PlanService.findAll (package:flutter_app/modules/main/model/db/biz/plan_service.dart:21:13)
    flutter: <asynchronous suspension>
    flutter: #8      TaskExecutor.execute.<anonymous closure> (package:load_data/src/task_helper.dart)
    flutter: <asynchronous suspension>

fix it
in sqflite_database_factory.dart

     extension DatabaseFactoryExtension on DatabaseFactory {
      Future<String> getDatabasePath(final String name) async {
        return join(await getDatabasesPath(), name);
      }
    }

change into

     extension DatabaseFactoryExtension on DatabaseFactory {
      Future<String> getDatabasePath(final String name) async {
        return join(await sqfliteDatabaseFactory.getDatabasesPath(), name);
      }
    }

**Comment by vitusortner** [comment]
Thanks for your report! A fix is on its way.
