### ISSUE TITLE
Destructive option on version increase rather than requiring migration

### ISSUE THREAD

**Issue by rpekarek** [vitusortner/floor#486]
In Room on Android we have an option to `fallbackToDestructiveMigration()`, meaning we don't have to supply a migration on version update, the database is simply torn down and recreated with the new schema.

This is a nice feature when using the database for caching, we don't necessarily want or need the old data forms when we update the schema

**Comment by vitusortner** [comment]
Hi! We're certainly interested in such a feature and a draft of it is available at #473. I'll close this issue as a duplicate of #356.
