### ISSUE TITLE
Using getter/setter as column

### ISSUE THREAD

**Issue by bdremynoel** [vitusortner/floor#489]
As I flatten sub-content on my models, I would keep some fields as queryable.

Let's take this sample:
```dart
@entity
class Foo {
  @primaryKey
  final int id;
  final String label;
  @TypeConverters([StatusConverter])
  final Status status;

  int get statusId => status?.id;
}

class Status {
  final int id;
  final String label;
}
```

StatusConverter converts this complex object to string, but I'd like to keep the `id` attribute in `Foo` data class.

As stated in documentation, getter is not mapped "by default", I tried to add `@ColumnInfo` but nothing is generated.

Is it implemented or always ignored? If this is available to achieve this ?

**Comment by vitusortner** [comment]
Hi! Sorry for the late reply. Do you want to store the `statusId` in its own column?

**Comment by bdremynoel** [comment]
Yes, without managing internal updates of this field.

**Comment by vitusortner** [comment]
As of now, this is not supported. What's your motivation behind this?

**Comment by bdremynoel** [comment]
As json1 is not supported, I wanted to keep few fields queryable from sub-tree.
Declaring `stateId` as a field and initializing it in constructor do the job for me.
