### ISSUE TITLE
Error in Entity with factory constructor

### ISSUE THREAD

**Issue by jlalfonso21** [vitusortner/floor#490]
I have an entity `Person` that works correctly, with its fields and default constructor.
```
@Entity(tableName: 'person')
class Person {
// ...
    Person(...);
}
```
 I needed to add other constructor for when the data comes in JSON and I add one to it, but when I execute the command `flutter packages pub run build_runner build` it gives me an error in the file that is generated since it is not passing parameters to the class constructor, even when ignoring it.

```
@ignore
factory Person.fromJson(Map<String, dynamic> json) {
    return Person(...);
}
```

Is this a bug or am I using the constructor incorrectly?

**Comment by vitusortner** [comment]
Hi! Can you send over the full class definition? Multiple constructors shouldn't be a problem. It's just important that there is one that initializes all properties of the class. Additionally, the constructor must be the **first one defined in the class**.

**Comment by mqus** [comment]
I'll assume that this problem was solved, since you did not answer for so long. If you have any updates, feel free to reopen this issue or create a new one :)
