### ISSUE TITLE
Migrate floor_generator's dependencies to null-safe versions

### ISSUE THREAD

**Issue by vitusortner** [vitusortner/floor#504]
We have recently migrated the codebase to support null-safety (#462). We're now generating null-safe code but floor_generator's internal dependencies aren't exclusively null-safe.

Migrate the dependencies to their null-safe versions once available and make sure to not run tests with `--no-sound-null-safety` anymore (CI).

- [x] build
- [x] build_config
- [x] build_test
- [x] code_builder
- [x] dart_style
- [x] source_gen

Additionally, make sure to get rid of the mockito (5.0.2) dependency override, which was introduced to make floor work with source_gen 1.0.0. The tracking issue for mockito can be found here: https://github.com/dart-lang/mockito/issues/373.

**Comment by rickydj** [comment]
Please, fix this as soon as possible, i cant build entities because i have problems with this as it cant be null safety, the system said: "Query method parameters have to be non-nullable. Define id as non-nullable."

**Comment by vitusortner** [comment]
> Please, fix this as soon as possible, i cant build entities because i have problems with this as it cant be null safety, the system said: "Query method parameters have to be non-nullable. Define id as non-nullable."

We're tracking this problem in a separate issue #507.
