### ISSUE TITLE
How to declare composite keys in Floor

### ISSUE THREAD

**Issue by eddydn** [vitusortner/floor#511]
Hello ! Can you show me how to declare composite primary keys in Floor DAO ?

**Comment by dkaera** [comment]
Hello @eddydn 
The primary keys are managed by the `@Entity` annotation, you can find more information about the primary key declaration here - https://vitusortner.github.io/floor/entities/#primary-keys

**Comment by mqus** [comment]
I'll assume that this problem was solved, since you did not answer for so long. If you have any updates, feel free to reopen this issue or create a new one :)
