### ISSUE TITLE
build_runner 2 not compatible with floor_generator

### ISSUE THREAD

**Issue by demos77** [vitusortner/floor#541]
With the new update of build_runner 2.0.0 with null safety floor_generator is not compatible.

`
Because build_runner >=2.0.0 depends on code_builder ^4.0.0 and floor_generator 1.0.1 depends on code_builder ^3.7.0, build_runner >=2.0.0 is incompatible with floor_generator 1.0.1.`

How to do ? Do you prepare a new version ?

**Comment by vitusortner** [comment]
We'll look into updating build_runner as soon as possible. Have you checked if pub's dependency overrides can help? https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by demos77** [comment]
With your advice i have trying this, but not work

`dependency_overrides:
  code_builder: ^4.0.0`

**Comment by proninyaroslav** [comment]
@demos77 
You also need to override this:
```
build_config: '>=1.0.0 <1.1.0'
```

**Comment by demos77** [comment]
ok it's work for the moment, the time you upgrade :)

**Comment by demos77** [comment]
When do you make a new version / tag ?
