### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by Bunny1376** [vitusortner/floor#547]
hi, i am using floor database and i want to set some migrations on my data base , but when i create a migration like this:
    final migration1to2 = new Migration(1, 2, (database) async {
      await database.execute('ALTER TABLE user ADD COLUMN name3 TEXT');
    });

the database parameter has null value some times, and some times it pass this line but on .addMigrations([migration1to2]) inside generator method the _migrations array has empty array value,
could you please help me to solve this problem ?

additinal info : 
floor: ^0.18.0
Flutter (Channel stable, 1.22.6)

**Comment by cassioseffrin** [comment]
your migration script seems to be Ok, add column is one the things SQLite accepts when you are altering a table in any versions. Check your database version, the migration (1,2) will run just once, after migration the new version will be stored in database and never gonna run again. I would recommend you to test your ALTER table in database IDE SQLiteStudio to test it before execution on migration script.

**Comment by cassioseffrin** [comment]
@Bunny1376 there is an amazing tool in android studio (above v4.1) called: database inspector may it gonna help you in some  case.

**Comment by Bunny1376** [comment]
@cassioseffrin hi, i got my problem 5 days ago,
when i call migration in main page , it work as well
