### ISSUE TITLE
How to Solve When I update the DataBase

### ISSUE THREAD

**Issue by JalorOo** [vitusortner/floor#556]
there is no example in demo,

the log in the console is `There is no migration supplied to update the database to the current version. Aborting the migration.`

and my code is 
```
@Database(version: 2, entities: [Mood,AddMood])
abstract class AppDatabase extends FloorDatabase {
  MoodDao get moodDao;
  AddMoodDao get addMoodDao;
}
```

please tell me how to fix it, thanks

**Comment by mqus** [comment]
See https://vitusortner.github.io/floor/migrations/ . Let us know if there is anything missing from the docs.

Writing a demo for this is not easy as we would have to provide 2 different timestamps from an app and use them together somehow

**Comment by JalorOo** [comment]
thank you！

**Comment by VipsDevelopment** [comment]
@mqus  the URL which you provided https://vitusortner.github.io/floor/migrations/ is not opening 

<img width="645" alt="Screen Shot 2022-09-21 at 5 36 53 PM" src="https://user-images.githubusercontent.com/110459356/191499636-fb02d450-f8b4-4a69-9773-72fd1051eeef.png">

**Comment by dkaera** [comment]
> @mqus  the URL which you provided https://vitusortner.github.io/floor/migrations/ is not opening 
> 
> 
> 
> <img width="645" alt="Screen Shot 2022-09-21 at 5 36 53 PM" src="https://user-images.githubusercontent.com/110459356/191499636-fb02d450-f8b4-4a69-9773-72fd1051eeef.png">
> 
> 

please use https://pinchbv.github.io/floor/migrations/ instead
