### ISSUE TITLE
Transaction: a nullable return type becomes not nullable in the method's implementation

### ISSUE THREAD

**Issue by Mabsten** [vitusortner/floor#557]
Step to reproduce the issue:
- add this simple method to the TaskDao class in the official [example](https://github.com/vitusortner/floor/blob/develop/example/lib/task_dao.dart)

  ```dart
  @transaction
   Future<Task?> test(int id) {
     return findTaskById(id);
   }
  ```
- run `flutter pub run build_runner build`

Generated code:
```dart
  @override
  Future<Task> test(int id) async {
    if (database is sqflite.Transaction) {
      return super.test(id);
    } else {
      return (database as sqflite.Database)
          .transaction<Task>((transaction) async {
        final transactionDatabase = _$FlutterDatabase(changeListener)
          ..database = transaction;
        return transactionDatabase.taskDao.test(id);
      });
    }
  }
```

This code doesn't compile because the method is declared with a not nullable return type, and also `sqflite.Database.transaction<Task>(..)` (in the else branch) is invoked with a not nullable parametric type

**Comment by StarkShang** [comment]
This append is 1.2.0 again even with annotation on top of database.dart file: 
 

> //@dart=2.12
