### ISSUE TITLE
NoSuchMethodError on select partial data of column.

### ISSUE THREAD

**Issue by wangmir** [vitusortner/floor#564]
Currently I'm using 0.19.1 to avoid null-safety.

I faced the problem of floor generator when the return type is not matched with the entity.

something like,

```
@Query(SELECT message FROM Db);
Future<List<String>> getMessages();
```

I realized that when I changed the API into,
```
@Query(SELECT * FROM Db);
Future<List<Entity>> getMessageEntities();
```

Can u give me any solution about this?

**Comment by mqus** [comment]
Floors queries currently only supports returning entity or view classes(or void), not simple types like string or int.

**Comment by wangmir** [comment]
> Floors queries currently only support returning entity or view classes(or void), not simple types like string or int.

Oh, ok.. I should use entry for now.
