### ISSUE TITLE
Has this library abandoned maintenance? Haven't seen the update for a long time

### ISSUE THREAD

**Issue by T-Oner** [vitusortner/floor#577]

**Comment by marcjoha** [comment]
@vitusortner @mqus anything to share on this? I need support for JOIN statements, and starting to wonder if I might need to look for alternative libraries. Would be a real shame, I really like the semantics and structure of this one and think you've done an amazing job so far.

**Comment by vitusortner** [comment]
Hi, thanks for bringing this up! To begin with, the maintenance has not been abandoned. The last months have been super busy and I'm looking forward to spending more time working on improvements again soon.
To speed this process up, we need your support. Tell us about the problems you're facing and the features you're wishing for. In case you're interested in helping manage the community around the library or ship updates – we're always happy about contributions.

**Comment by T-Oner** [comment]
@vitusortner I need a release version, #531 has been merged for a long time. But there has not been a release version, and now I use source code integration, which is a bit inconvenient. Thanks.

**Comment by marcjoha** [comment]
@vitusortner That's wonderful news, thanks for letting us know. The one problem I hit repeatedly is, at its core, covered by  #94.

**Comment by pawelsa** [comment]
@T-Oner I am not sure what exactly do you need, but maybe this will be helpful `'SELECT * FROM contacts ORDER BY firstName || " " || lastName'`, when done in this manner code is generated correctly

**Comment by ErliSoares** [comment]
I wanted to have time to help with the development, I developed several more advanced features here https://github.com/ErliSoares/floor

But it's very dirty code with a lot of bugs, it needs to be improved to integrate with the main branch.

Feature implemented for dynamic filter
https://github.com/ErliSoares/floor/blob/develop/floor_annotation/lib/src/load_options/load_options_entry.dart
