### ISSUE TITLE
Migrate analyzer to 2.x

### ISSUE THREAD

**Issue by proninyaroslav** [vitusortner/floor#594]
Conflict in floor_generator:

`Because floor_generator 1.1.0 depends on analyzer ^1.2.0 and no versions of floor_generator match >1.1.0 <2.0.0, floor_generator ^1.1.0 requires analyzer ^1.2.0.`

**Comment by quinnjr** [comment]
Having the same issue when attempting to use `floor_generator` alongside `injectable_generator`.

**Comment by proninyaroslav** [comment]
As a workaround:
```Dart
dependency_overrides:
  analyzer: ^2.2.0
```

**Comment by vitusortner** [comment]
Closed by #598
