### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by zhuangtao97** [vitusortner/floor#608]
final migrationVersion = Migration(1, 2, (database) async {
  await database.execute('ALTER TABLE KimEvent ADD COLUMN calendarName TEXT');
});

error:
DatabaseException(Error Domain=FMDatabase Code=1 "duplicate column name: calendarName" UserInfo={NSLocalizedDescription=duplicate column name: calendarName}) sql 'ALTER TABLE KimEvent ADD COLUMN calendarName TEXT' args []}

**Comment by dmitdu** [comment]
Hi! How did you fix it? I have same issue now.
