### ISSUE TITLE
Blank screen when using msix packager with floor

### ISSUE THREAD

**Issue by ayalma** [vitusortner/floor#615]
Hi 
When we trying to use msix builder package with our floor base app
When we run app after installation
We get just blank white screen

**Comment by MrCsabaToth** [comment]
Any console error logs, debug logs?

**Comment by ayalma** [comment]
Application is in release mode and there is no error logs

**Comment by ayalma** [comment]
I think this is the clue for problem 
[https://github.com/tekartik/sqflite/issues/574]()

**Comment by MrCsabaToth** [comment]
The link properly: https://github.com/tekartik/sqflite/issues/574

**Comment by ayalma** [comment]
I used this issue for injecting sqlite.dll to my msix package 
and i just tested my sqlite.dll loading by running in release mode from terminal 
and every thing was good 
but when i packaged my app via msix 
i still got blank screen

**Comment by ayalma** [comment]
After some search and doc reading 
I found out that default db path is point to application directory 
And when we bundle our application with msix 
it put app to
```
C:\Program Files\WindowsApps 
```
And because permission issue of this folder we get error.
Also when we using  floor in desktop release mode 
App cant find sqlite3.dll and this Couse  error
I just use this code to fix issue , but it will be good if floor provide some api for that
```
Future<AppDatabase> _initDatabse() async {
  if (defaultTargetPlatform == TargetPlatform.windows && !kDebugMode) {
    open.overrideFor(OperatingSystem.windows, _openSqliteUnderWindows);
    final db = sqlite3.openInMemory();
    db.dispose();
    // Change the default factory
    databaseFactory = databaseFactoryFfi;
  }

  
  Directory tempDir = await path.getApplicationSupportDirectory();
  String tempPath = tempDir.path;

  sqfliteDatabaseFactory.setDatabasesPath(tempPath);
  Bloc.observer = CGposBlocObserver();

  final database =
      await $FloorAppDatabase.databaseBuilder('cgpos_db.db').build();
  return database;
}

DynamicLibrary _openSqliteUnderWindows() {
  var path = "";
  try {
    final libraryNextToScript = File('dlls/sqlite3.dll');
    path = libraryNextToScript.path;
    stderr.writeln('Failed to load sqlite3.dll at $path');
    return DynamicLibrary.open(path);
  } catch (e) {
    stderr.writeln('Failed to load sqlite3.dll at $path');
    rethrow;
  }
}
```

**Comment by waqarorakzai** [comment]
To someone facing the issue:
Go to the database.g.dart file or whatever the name of the file you have given:
replace build method with this on
`Future<AppDatabase> build() async {
    final p = await PathProviderWindows().getApplicationDocumentsPath();
    final path = name != null
        ? p! + '/' + name!
        : ':memory:';
    final database = _$AppDatabase();
    database.database = await database.open(
      path,
      _migrations,
      _callback,
    );
    return database;
  }
}`

**Comment by SteveCruise** [comment]
mark mark
