### ISSUE TITLE
count statement should return number but it got NULL

### ISSUE THREAD

**Issue by xwanlion** [vitusortner/floor#625]
abstract dao class:
~~~dart
  @Query('SELECT count(1) num FROM v_todo where deleted = 0 and state = :state')
  Future<int?> count(int state);
~~~

generated dao class:
~~~dart
@override
  Future<int?> count(int state) async {
    await _queryAdapter.queryNoReturn(
        'SELECT count(1) num FROM v_todo where deleted = 0 and state = ?1',
        arguments: [state]);
  }
~~~

why is queryNoReturn, not a number?

**Comment by MrCsabaToth** [comment]
The support of scalar return values need some development. See #576

**Comment by MrCsabaToth** [comment]
Ultimately #200 will introduce a new SQL query analyzer to support cases like this. Major change.

**Comment by xwanlion** [comment]
> analyzer

all right

**Comment by xwanlion** [comment]
all right

**Comment by MrCsabaToth** [comment]
Unfortunately https://github.com/vitusortner/floor/pull/361 got abandoned, need to be rewritten from scratch
