### ISSUE TITLE
`floor.codes` Website is down

### ISSUE THREAD

**Issue by arif2k17** [vitusortner/floor#633]
`floor.codes` Website is down

**Comment by vitusortner** [comment]
thanks for the report. the site is working for me. can you make sure to clear cookies and also share some more details?

**Comment by PcolBP** [comment]
For me website runs only on mobile phone, while on desktop is down.
![image](https://user-images.githubusercontent.com/67896443/149767436-521f435b-9076-42c3-be0d-87116766a4c1.png)

**Comment by vitusortner** [comment]
closing this for now. feel free to reopen the ticket if the problem surfaces again.

**Comment by BigLiao** [comment]
@vitusortner website is down, domain `floor.codes` does not exist?

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/22113206/169996154-7daf894f-b312-4f08-91bd-ebc65e54f351.png">

https://www.nslookup.io/domains/floor.codes/dns-records/#google

**Comment by vitusortner** [comment]
thanks for the report! please refer to [vitusortner.github.io/floor/](https://vitusortner.github.io/floor/) until renewed our domain.

**Comment by tulioccalazans** [comment]
Website is down (https://floor.codes/)
