### ISSUE TITLE
"floor_generator" analyzer outdated

### ISSUE THREAD

**Issue by mainser** [vitusortner/floor#639]
There is a problem when updating the dependencies, in the case in question, the version of the analyzer that has the "floor_generator" is outdated.

I attach the console output when updating the libraries:

`
Because retrofit_generator >=4.0.0 depends on analyzer ^3.0.0 and floor_generator 1.2.0 depends on analyzer ^2.2.0, retrofit_generator >=4.0.0 is incompatible with floor_generator 1.2.0.
And because no versions of floor_generator match >1.2.0 <2.0.0, retrofit_generator >=4.0.0 is incompatible with floor_generator ^1.2.0.
So, because anuncios depends on both floor_generator ^1.2.0 and retrofit_generator ^4.0.1, version solving failed.
pub get failed (1; So, because anuncios depends on both floor_generator ^1.2.0 and retrofit_generator ^4.0.1, version solving failed.)
exit code 1
`

**Comment by Cilestal** [comment]
You can use a temporary fork of the repository

 floor_generator:
    git:
      url: git://github.com/Cilestal/floor.git
      ref: develop
      path: floor_generator/
