### ISSUE TITLE
Support  Analyzer 4

### ISSUE THREAD

**Issue by fnicastri** [vitusortner/floor#659]
Upgrade analyzer to v 4 please

**Comment by Amir-P** [comment]
You can use this fork for now: https://github.com/Amir-P/flat. I've added support for Analyzer 4. @fnicastri

**Comment by fnicastri** [comment]
@Amir-P Thanks!

**Comment by MrCsabaToth** [comment]
Badly needed!

**Comment by vyendn3** [comment]
Looking for update

**Comment by dkaera** [comment]
Hey guys, long time no see 😄
Pushed a migration [PR here](https://github.com/vitusortner/floor/pull/666)
But have no idea how to solve the faced CI errors.
All tests are passing well, but `test_cov` throws an error.  @vitusortner can you help to solve it, please?

**Comment by ThomasMiddel** [comment]
Hey all! I'm currently collaborating with Vitus to get Floor up and running again, I [opened a PR](https://github.com/vitusortner/floor/pull/662) to support analyzer 4.1.0 and fixed the CI issues just now. The idea is to get this merged ASAP and roll out an update within a couple of days. 

Thanks for the contribution @dkaera! I'll check out the PR together with Vitus, maybe there's some stuff we can use there that we did differently 🙏

**Comment by dkaera** [comment]
Thanks, @ThomasMiddel 👍
So let's push this project 😄
